### ISSUE TITLE
$ref syntax or other?

### ISSUE THREAD

**Issue by simlu** [eemeli/yaml#1]
Following this project with interest!

Are you planning to support resolving and loading external yaml files somehow?

**Comment by eemeli** [comment]
Do you mean an inline reference to a file or URL in one YAML file being loaded during the file's resolution? That's not a feature in existing YAML spec, and as far as I know, it's not on the roadmap for YAML 1.3 or even YAML 2. Could you point me towards a reference for this somewhere? If you're interested in getting something like this included in the spec, you should submit an [RFC](/yaml/yaml-spec/wiki/YAML-RFC-Index) for it.

Technically something like what you propose could be implemented as a custom data type that would then be included in the schema, but the security implications are significant enough that it would need to be separately loaded and enabled.

**Comment by simlu** [comment]
@eemeli Hey! Sorry, I should have clarified. No this is (unfortunately) not part of the yaml specs.

The $ref syntax is described here: https://github.com/json-schema-org/json-schema-spec/issues/514

My preference would be to have something similar added to this repo. Having it disabled / not loaded by default is perfectly fine. However writing it completely separate might also be an option.

-------------

We've been looking closely at this repo from various serverless issues and when config loading is restructured this repo would be a potentially dependency. Will get back here at some point.

**Comment by eemeli** [comment]
Closing this as a won't-fix issue for now. It's rather unlikely that I'd get to this myself in any sensible timeframe, but I'm not opposed to having it implemented as an extension; I'm pretty sure that the `resolve(doc, node): any` method used by the schema could be stretched to cover this.

It's also tbh unlikely that something like this would make sense including in the core repo, as loading external files seems like a rather likely point of failure regarding security.

**Comment by simlu** [comment]
@MikeRalphson We started using yaml-boost (disclaimer, I'm the auther), as it handles various cases nicely for us. Thank you for the reply though. Very interesting and I hadn't seen it before!
