### ISSUE TITLE
Disable logs

### ISSUE THREAD

**Issue by AndreaAdvanon** [eemeli/yaml#100]
How can I parse a string without warnings etc be logged to stdout? I don't see any options here https://eemeli.org/yaml/#options.

EDIT: from a quick look at the code it doesn't seem to be possible. Would this be something you plan to implement anytime soon?

**Comment by AndreaAdvanon** [comment]
Don't try this at home, but here's a workaround for now:

```js
const YAML = require('yaml');
const warn = console.warn;
console.warn = () => {};
const parsed = YAML.parse(content);
console.dir(parsed);
console.warn = warn;

```

**Comment by eemeli** [comment]
To avoid a warning, you can effectively do the same as what `YAML.parse()` does internally:
```js
YAML.parseDocument('!foo bar').toJSON()
// 'boo', without warnings
```

That'll still throw if the document has any errors, but it'll silently ignore the warnings.

Overall, the `yaml` API tries to do the "right thing" as much as possible, and to some extent that's driven by developer ergonomics but also by spec compliance, which actually specifies and requires those warnings. So `YAML.parse()` will work for most simple cases, while `YAML.parseDocument()` gives you more options and flexibility.
