### ISSUE TITLE
Apply conversion for value that matches regex

### ISSUE THREAD

**Issue by AndreaAdvanon** [eemeli/yaml#101]
I'm not sure if there's a way to do so currently.
I have a yaml file with some timestamps:
```yml
created_at: 2018-03-13 08:51:54.654332512 Z
```

Is there any way to have this value converted to `Date`?
Maybe applying a regex, for example? Would be very expensive to do so but still.

**Comment by eemeli** [comment]
What you're looking for is the `!!timestamp` tag that's a part of YAML 1.1 schema, but not of the core YAML 1.2 schema. If you're okay with following the 1.1 version of the spec (there are [differences](https://eemeli.org/yaml/#version-differences)), the easiest way to get a `Date` object out of your input is by specifying the schema:

```js
const src = 'created_at: 2018-03-13 08:51:54.654332512 Z'
const obj = YAML.parse(src, { version: '1.1' })
obj.created_at instanceof Date === true
```

If you'd prefer to keep the 1.2 semantics and just add date handling with a custom tag, here's how to do that:
```js
import { timestamp } from 'yaml/types/timestamp'

const src = 'created_at: 2018-03-13 08:51:54.654332512 Z'
const obj = YAML.parse(src, { tags: [timestamp] })
obj.created_at instanceof Date === true
```

Note that the latter API should be getting a bit simpler with the next release, but it's not quite ready yet.
