### ISSUE TITLE
Not working character escaping for #

### ISSUE THREAD

**Issue by dmitriym09** [eemeli/yaml#103]
Not working character escaping for #:
```javascript
const yaml = require('yaml');
const str = `name: test2 \\#1
val: test #121328`;
console.log(yaml.parse(str));
```

Now out:
```json
{ "name": "test2 \\#1", "val": "test" }
```
I think it must be so:
```json
{ "name": "test2 #1", "val": "test" }
```
It`s bug? Can I create pull-request for fix this bug?

**Comment by eemeli** [comment]
That's not a bug; it's working as intended. [According to the spec](https://yaml.org/spec/1.2/spec.html#id2787109), the only scalar style that does `\` escaping is the "double-quoted" style. With the plain (unquoted) style, it's not possible to include a space-separated `#` in the value. Therefore `yaml` stringifies e.g. your "must be so" example like this:

```js
const obj = { "name": "test2 #1", "val": "test" }
console.log(YAML.stringify(obj))
// 'name: "test1 #1"\nval: test\n'
```
