### ISSUE TITLE
Types based on Pair

### ISSUE THREAD

**Issue by dotevo** [eemeli/yaml#106]
Hello,

I want to create own type. Very similar to Pair but I have no idea what I'm doing wrong.

```
class Own extends Pair {
  constructor() {
    super(new Scalar('a'), new Scalar('b'))
    console.log('a')
  }
  toJSON(_, ctx) {
    return 'v'
  }

  toString(ctx, onComment) {
    return '!ref ';
  }
};

const own = {
  identify: value => value.constructor === Own,
  default: true,
  nodeClass: Own,
  tag: '!own',
  resolve: function(doc, cst) {
    console.log('aaa')
    return new Own();
  },
  stringify(item, ctx, onComment, onChompKeep) {
    return 'a';
  }
}
```

```
  console.log node_modules/yaml/dist/Document.js:551
    [ { TypeError: Class constructor Pair cannot be invoked without 'new'
        at new Ref (/...:12:5)
```

Is it possible to use base class?

**Comment by eemeli** [comment]
Extending `Pair` is tricky, especially if you're looking to be ably to parse YAML source directly into your object. `Merge` does this, but its parsing is packaged within `Map` parsing. Arguably this could be modularised, if there was a good use case. Also do note that a pair can't itself have a tag, as it's not an independent entity in YAML.

Could you explain a bit about what you're looking to do with your `Own` pair-ish type?

**Comment by dotevo** [comment]
I've tried to create own merge type with the reference path. Something like:

```
a:
  b:
    c: TEST
w: !ref ./a/b/c
```

And I had tried with the YAMLMap before with the same result:
```
  console.log node_modules/yaml/dist/Document.js:551
    [ { TypeError: Class constructor YAMLMap cannot be invoked without 'new'
        at new Own (...:12:5)
```
The case is to create any own type based on the basic one. 

Probably I'm doing something wrong but I cannot find the solution.

**Comment by eemeli** [comment]
Are you really sure that you need to do this? As in, I'm doubtful that you really have a use case that could not be solved by the existing anchor/alias/merge node syntax.

But okay, besides that there are at least three separate problems that I think you need to solve if you wish to proceed, and I'd recommend tackling these one at a time:
1. Defining an alternative Alias node type. The core Alias node is hooked pretty deeply in the node resolution functions, and I'd be surprised if you could avoid that with a custom pathlike reference type.
2. Figuring out how and when you resolve the value of a reference path. AST nodes don't have a `parent` link (in your example, `w` doesn't know that it's adjacent to `a`), so you'll almost certainly need to base all paths at the document root.
3. Defining an alternative Merge node type, and figuring out how to resolve its values.

With the current architecture, it might be easiest for you write your own `YAML.parse()` equivalent that would first call `YAML.parseDocument()`, then find and iterate through your reference merge pairs and apply their effects to the document, before calling its `toJSON()` method to produce JS object output -- or just working directly with the resulting AST nodes, in case you need to modify the values programmatically and possibly stringify them.

**Comment by dotevo** [comment]
Thank you for explanation. I will try to think about it again.

I have it almost done like:
```
class Ref /*extends Collection*/{
  private mPath: string;
  private mDoc: Document;
  constructor(doc: Document, path: string) {
    // super(); # ERROR
    this.mPath = path;
    this.mDoc = doc;
  }
  toJSON(_, ctx) {
    return this.mDoc.getIn(this.mPath.split('/')).toJSON();
  }

  toString(ctx, onComment) {
    return '!ref ' + this.mPath;
  }
};

const ref = {
  identify: value => value.constructor === Ref,
  default: true,
  nodeClass: Ref,
  tag: '!ref',
  resolve: function(doc, cst) {
    return new Ref(doc, cst.strValue);
  },
  stringify(item, ctx, onComment, onChompKeep) {
    return stringify({ value: item.toString() }, ctx, onComment, onChompKeep)
  }
}

export default ref;
```

```
a: &a
    P:
      W: A

b: !ref a/P
```
is changed into:

```
{ a: { P: { W: 'A' } }, b: { W: 'A' } }
```


I'm using 1.4.0 version from npmjs.org. Why do I want to extend existing classes? For example it will be possible to implement getIn from Collection and I hope that doc.getIn(['b','W']) will work fine.

**Comment by dotevo** [comment]
@eemeli Please take a look into: 
https://stackoverflow.com/questions/51860043/javascript-es6-typeerror-class-constructor-client-cannot-be-invoked-without-ne/51860850

It looks like similar problem to mine. I cannot extend classes.

**Comment by dotevo** [comment]
yep. I've used wrong es. Thank you

**Comment by dotevo** [comment]
@eemeli 
Could you find a minute to review my initial commit for interfile ref support:
https://github.com/dotevo/yaml-refs

Example:
```
a: &a
    aa:
      aaa: val

b: !ref ./include.yml#object
```
include.yml:
```
object:
  a: 1
  b: 2
  c: 3
```
is changed to:
``` {"a": {"aa": {"aaa": "val"}}, "b": {"a": 1, "b": 2, "c": 3}} ```

I know that the 'issue' is not the best place to ask about it. But I do not want to create a new one.
