### ISSUE TITLE
how to preserve original formatting

### ISSUE THREAD

**Issue by akosyakov** [eemeli/yaml#110]
I would like to parse a document, remove several ast elements and serialize it to a file. I don't want to change formatting of the whole document. Is it possible?

**Comment by eemeli** [comment]
Yes, if you're okay working with the [CST parser](https://eemeli.org/yaml/#cst-parser) API, and you're careful about what you're doing. Stringifying the CST will use the original characters, except for the nodes for which you specify a `value`. Do note that the CST API for collections in particular is a bit burdensome, as it needs to be able to handle even broken YAML.

Working with the AST level is much nicer, but from there the stringifier no longer takes into account the original source, and instead uses its own rules for formatting, in particular for indentation.

If you're interested in fixing this, I'd welcome a proposal for how to preserve and use indentation information from the source at the AST level.

**Comment by akosyakov** [comment]
So i can:
- parse a document with keep CST
- use document AIP to find AST nodes which should be removed
- remove CST nodes associated with found AST nodes
- serialize CST tree

like that?

In order to remove CST nodes from a collection would it be enough to remove them from `items`?

**Comment by akosyakov** [comment]
It worked, thx!
