### ISSUE TITLE
Parsing a string that looks like a number seem to not work

### ISSUE THREAD

**Issue by nulltoken** [eemeli/yaml#118]
Hello,

```
console.log(require("yaml").parse("example: 0681924019"))
```

returns

```
{ example: 681924019 }
```

Would there be a way to parse the value of `example` as a string?

My understanding of the [spec](https://yaml.org/spec/1.2/spec.html#id2803828) is that it shouldn't be considered as an integer as it doesn't match the ` 0|-?[1-9][0-9]*` regexp

**Comment by eemeli** [comment]
The part of the spec that you're linking to is the JSON Schema integer, which has a different definition than the default [Core Schema](https://yaml.org/spec/1.2/spec.html#id2804923) integer, which detects numbers according to the pattern `[-+]?[0-9]+`.

In your case, just [switching](https://eemeli.org/yaml/#options) to the JSON schema probably isn't what you're looking for, as it does not support scalar tag resolution for non-specific tags (and hence will fail when encountering `example`). In other words, it works just like JSON in this respect. On the other hand, the [Failsafe Schema](https://yaml.org/spec/1.2/spec.html#id2802346) might be suitable, as it considers *all* scalars to have string values:

```js
YAML.parse('example: 0681924019', { schema: 'failsafe' })
// { example: '0681924019' }

**Comment by nulltoken** [comment]
Amazingly detailed answer! Thanks.
