### ISSUE TITLE
Implicit map keys need to be followed by map values

### ISSUE THREAD

**Issue by notiv-nt** [eemeli/yaml#120]
Error:

![image](https://user-images.githubusercontent.com/10743009/65151788-76070380-da2f-11e9-9f03-65272dbccef5.png)

Ok: 

![image](https://user-images.githubusercontent.com/10743009/65151864-9a62e000-da2f-11e9-862f-134311f395ce.png)
![image](https://user-images.githubusercontent.com/10743009/65151883-a2228480-da2f-11e9-9a76-fa8d745fceb8.png)

The error appears only if the very last character is `:`

I'm not so sure it should be?

```javascript
const YAML = require('yaml');
const text = require('fs').readFileSync('./doc.yaml', { encoding: 'utf8' });
const cst = YAML.parseCST(text);
const doc = new YAML.Document();

let a = doc.parse(cst[0]);

console.dir(a.errors); //
```

```yaml
test:
  - test1: test1
    test2:
```

https://repl.it/@MikeWild/MammothFortunateDatamining

**Yaml** v 1.6.0

**Comment by eemeli** [comment]
I'm pretty sure that this was indeed a bug in the CST parser. Specifically, it was only terminating a plain-value node at a `:` if the subsequent character was whitespace, but not if it the input ended there. Now it does. This changes the handling of the following minimal case:

```js
// before
YAML.parse('a:') // 'a:'

// after
YAML.parse('a:') // { a: null }

// unchanged
YAML.parse('a:\n') // { a: null }
```

The specific spec construct that's being handled here is [`c-l-block-map-implicit-value(n)`](https://yaml.org/spec/1.2/spec.html#c-l-block-map-implicit-value(n)) which can, when you trace all of its possible values, match the following:

```
c-l-block-map-implicit-value(n) ::= “:” ( s-l+block-node(n,block-out) | ( e-node s-l-comments ) )
e-node ::= e-scalar ::= /* Empty */
s-l-comments ::= ( s-b-comment | /* Start of line */ ) l-comment*
s-b-comment ::= ( s-separate-in-line c-nb-comment-text? )? b-comment
b-comment ::= b-non-content | /* End of file */
```

I'd missed the final step there, which allows for `“:” /* End of file */` to be considered a valid implicit value.

**Comment by notiv-nt** [comment]
@eemeli can you make a release ?

**Comment by eemeli** [comment]
@notiv-nt Will do, once #122 is resolved.
