### ISSUE TITLE
Atom missing module ./dist

### ISSUE THREAD

**Issue by bstark70** [eemeli/yaml#123]
I'm trying to use your yaml tool in ATOM and it says that a module is missing ./dist is that a directory that you didn't include in the repository or a required library?

**Comment by eemeli** [comment]
Could you specify which version of `yaml` you're experiencing this with, and what the exact error is?

**Comment by bstark70** [comment]
1.6.0

**Comment by bstark70** [comment]
require('yaml')
Error: Cannot find module './dist'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:594:15)
    at Function.Module._load (internal/modules/cjs/loader.js:520:25)
    at Module.require (internal/modules/cjs/loader.js:650:17)
    at require (internal/modules/cjs/helpers.js:20:18)

**Comment by eemeli** [comment]
That's weird. Could you verify in your file system that you do have a directory `node_modules/yaml/dist` present, and that it contains `index.js` among other files? Those are included in a fresh install from npm at least.

**Comment by bstark70** [comment]
I can't install using npm or Atom's apm that is npm, as this is a computer system at work that has no access to the internet. I have to download it from git and have are security scan it and transfer it to that system. How would you have to do it manual on Atom?

**Comment by eemeli** [comment]
Ah, that's a rather important detail. If you're installing from git, you should follow [these instructions](https://github.com/eemeli/yaml/blob/master/CONTRIBUTING.md#getting-started) to get a full environment set up, and then run `npm pack` to create a tarball with the files that are needed.

**Comment by bstark70** [comment]
I got it to work took a bit but it is thanks for your info.
