### ISSUE TITLE
Allow to use setIn for deep-nested values

### ISSUE THREAD

**Issue by andresmgot** [eemeli/yaml#131]
Hi!

When using `Documents`, sometimes I need to set a value which parent node doesn't exists (yet) but that ends up in an error:

```
> d = yaml.parseDocument("foo: bar")
Document {
...
> d.setIn(["a", "b"], 1)
Error: Expected YAML collection at a. Remaining path: b
```

The above can be done executing `d.setIn(["a"], {b: 1})` but I was thinking that it would be helpful for the method `setIn` to do that for you, similar to how lodash works:

```
> a = {b: 1}
{ b: 1 }
> lodash.set(a, "c.d", 2)
{ b: 1, c: { d: 2 } }
```

Do you think this is something doable? Thanks in advance!

**Comment by eemeli** [comment]
That could work. There's a corner case that'll need to be settled with a path like `['foo', 3]`: Should the created object be a map or a sequence?

**Comment by eemeli** [comment]
Finally got around to implementing this. Went with non-negative integer keys creating sequences + everything else creating maps, as that's what Lodash also does.
