### ISSUE TITLE
Date string and stringify method

### ISSUE THREAD

**Issue by gigaga** [eemeli/yaml#132]
Hi,

I've an issue with `stringify` method on date field.

```javascript
const objTest = {
   startDate: '2019-12-01',
};

console.log(YAML.stringify(objTest));
```

returns `startDate: 2019-12-01` rather `startDate: '2019-12-01'`.

Best regards,

**Comment by eemeli** [comment]
The default for schema `yaml` uses is the YAML 1.2 core schema, which does not include `!!timestamp`. If you'd like to also support YAML 1.1 parsers, you can use the `version: '1.1'` or `schema: 'yaml-1.1'` [options](https://eemeli.org/yaml/#options).

**Comment by gigaga** [comment]
Ok thanks! I changed by using another node module `yamljs`

**Comment by qraynaud** [comment]
It's a bit late, but I'd argue that even if the schema does not mention a date type, the spec is contradictory on this point. It does say date are supported in `1.2` as showcased in `Example 2.22` that I repruduce here:
```yaml
canonical: 2001-12-15T02:59:43.1Z
iso8601: 2001-12-14t21:59:43.10-05:00
spaced: 2001-12-14 21:59:43.10 -5
date: 2002-12-14
```

It also implies that it is a full fledged type in section `Example 2.23` :
```yaml
not-date: !!str 2002-04-28
# …
```

If you have to say `!!str` for it not to be a `date`, then without it it can't be a `str` by default!

You should add the timestamp back and it should produce `Date` object.

**Comment by eemeli** [comment]
That section of the YAML 1.2 spec looks like it's the same as the [YAML 1.1 spec text](https://yaml.org/spec/1.1/#id858600), which did include a [!!timestamp](https://yaml.org/type/timestamp.html) tag. The [YAML 1.2 core schema](https://yaml.org/spec/1.2/spec.html#id2804923) does not. With the core schema, parsing the example 2.22 document will result in a map with string keys and values.

Admittedly the spec isn't clear on this, but it doesn't mean that timestamps are a part of any of the recommended YAML 1.2 schemas. To include them in `yaml`, use the [`customTags` option](https://eemeli.org/yaml/#built-in-custom-tags).

**Comment by qraynaud** [comment]
Well, this is also debatable. This is written in `10.04` section:
`
It is strongly recommended that such schemas be based on the core schema defined above. In addition, it is strongly recommended that such schemas make as much use as possible of the the YAML tag repository at http://yaml.org/type/. This repository provides recommended global tags for increasing the portability of YAML documents between different applications..
`

The provided page points to the `1.1` type definitions. What I think it says is that it is recommended for parsers to implement both `core schema` and `1.1 tags` as global tags for `1.2` parsing, keeping `1.1` document valid (this makes sense in a way).

**Comment by perlpunk** [comment]
It says:
> This [the Core Schema] is the recommended default schema that YAML processor should use unless instructed otherwise.

I think at least this sentence is pretty clear.
It was not intended that all the types from the type repository are implemented by default. Some of them even conflict with the 1.2 types.

So while it makes sense to implement (some of) the 1.1 types for compatibility, they should be optional.

**Comment by qraynaud** [comment]
Yes, that's a good argument. Thanks for your insights on this.
