### ISSUE TITLE
Stringify blocks as literal "|"

### ISSUE THREAD

**Issue by piascikj** [eemeli/yaml#134]
Is there a way to stringify blocks in literal format? e.g.
```yaml
block: |
  A block
  of text
```

**Comment by eemeli** [comment]
That's actually the default for your example, as the value is a multiline string:
```js
YAML.stringify({ block: 'A block\nof text\n' })
// block: |
//   A block
//   of text
```

If you would like to set the format manually, that's also possible. You'll need to create a YAML document with your object's value as its contents, and then set the `type` of the [scalar node](https://eemeli.org/yaml/#scalar-values):
```js
const doc = new YAML.Document()
doc.contents = YAML.createNode({ block: 'A line of text' })
String(doc)
// block: A line of text

const node = doc.get('block', true)
node.type = 'BLOCK_LITERAL'
String(doc)
// block: |-
//   A line of text
```

**Comment by eemeli** [comment]
Closing as answered.

**Comment by tiye** [comment]
any trick if I want to render all multiline strings in BLOCK_LITERAL without affecting all single line strings?
