### ISSUE TITLE
Add at index using collection methods

### ISSUE THREAD

**Issue by humandad** [eemeli/yaml#135]
It looks like you can use the add() and addIn() collection methods to add an item to the end of a sequence, but there's no way to add an item at a particular index as a far as I can tell. Is there a way to do this?

**Comment by eemeli** [comment]
Apologies for the delay in answering; I've been travelling.

The best way to currently achieve what you want would be to get the parent collection, and then to apply array methods such as `splice()` on its `items` array. Would that work for you?

**Comment by humandad** [comment]
That works. Thanks!
