### ISSUE TITLE
stringify of an empty object returns invalid YAML

### ISSUE THREAD

**Issue by rocketraman** [eemeli/yaml#136]
```
YAML.stringify({})
```

outputs invalid YAML:

```
{}
```

**Comment by eemeli** [comment]
`{}` is an entirely valid representation of an empty set in YAML, which is a superset of JSON. In fact it's probably the only truly valid representation of an empty set.

**Comment by rocketraman** [comment]
Ok thanks. My problem is downstream then.

**Comment by inos123** [comment]
SELECT sql FROM sqlite_master WHERE type = "table" AND tbl_name = "CHECKED_OUT"; SELECT Professor_Name, Department, Max(Salary) FROM SALARIES GROUP BY Department;
