### ISSUE TITLE
cannot emit keys with null values

### ISSUE THREAD

**Issue by paleozogt** [eemeli/yaml#139]
Given this code:
```
// test.js

const yaml = require('yaml');

console.log(yaml.stringify({
   foo: null,
   bar: null
}));

console.log(yaml.stringify({
   foo: null,
   bar: ""
}));
```

I see some weird output:

```
$ node --version
v12.14.1

$ npm list | grep yaml
`-- yaml@1.8.0

$ node test.js
? foo
? bar

foo: null
bar: ""
```

I would have expected it to output:
```
foo: null
bar: null

foo: null
bar: ""
```

**Comment by eemeli** [comment]
That's actually perfectly valid YAML; `?` indicates an explicit key. An all-null-value mapping can be useful as a set, in which use the key values are not relevant; hence there's special-case handling like this that you've encountered.

If you'd like to avoid this, the [option](https://eemeli.org/yaml/#options) you're looking for is `simpleKeys`:

```js
const obj = { foo: null, bar: null }

YAML.stringify(obj)
// ? foo
// ? bar

YAML.stringify(obj, { simpleKeys: true })
// foo: null
// bar: null
```
