### ISSUE TITLE
parse does not properly handle floats of the form ".8"

### ISSUE THREAD

**Issue by ycz** [eemeli/yaml#144]
```
> yaml.parse('foo: .8')
{ foo: '.8' }
```
Here, the value of `foo` should be the number `0.8` instead of the string `'.8'`.

The 1.1 schema does work properly:
```
> yaml.parse('foo: .8', { schema: 'yaml-1.1' })
{ foo: 0.8 }
```

**Comment by eemeli** [comment]
Huh. You're right. I'm truly rather surprised that this hasn't been noticed before. Will fix ASAP.

Also, the trickier problem that this has surfaced for me is that I notice that the official [YAML 1.1 `!!float`](https://yaml.org/type/float.html) RegExp (which we use) is buggy, as it'll catch a solitary `.` as a "valid" float value:

```js
> YAML.parse('.', { version: '1.1' })
NaN
```

To be clear, that's entirely separate from this issue, but now I'm conflicted about what the right thing might be, to follow the spec (as we currently do), or "fix" the expression. :/

**Comment by jtbandes** [comment]
This regexp is a bit strange IMO: `(?:\.([0-9]+)|(?:0|[1-9][0-9]*)\.([0-9]*))` — is "`00.1`" not supposed to be a valid float?

**Comment by eemeli** [comment]
🤦‍♂️Yes, it is.

**Comment by eemeli** [comment]
Thank you @ycz and @jtbandes for pointing these out. It's been a while since someone discovered something so deeply wrong with this library.

**Comment by jtbandes** [comment]
Thanks for the quick responses!
