### ISSUE TITLE
Is `nodeIsJsonLike` defined?

### ISSUE THREAD

**Issue by BurtHarris** [eemeli/yaml#149]
In cst/FlowCollection.js reference is made to a function named `nodeIsJsonLike`, but I can't find it defined anywhere.   

Should this actually be using `jsonLike` as defined in Node.js?

**Comment by eemeli** [comment]
Thank you for spotting that! Thats should've been `prevNodeIsJsonLike`. I found a minimal test case that hits that bug, and fixed it.
