### ISSUE TITLE
Typescript re-write

### ISSUE THREAD

**Issue by Whoaa512** [eemeli/yaml#168]
Curious if this is on the roadmap or something that you'd consider for this project.

It would help keep the current type definitions more up to date and make it easier for others to contribute back fixes.

**Comment by eemeli** [comment]
Not actively planning on it, but not strictly opposed to it either. Particularly if someone else wants to take on the challenge. The codebase is in parts rather JavaScript-ish in a way that TypeScript isn't, so it's not necessarily straightforward.

For a more likely future direction, I'd really like to figure out a way of eventually not transpiling the source at all. Even now, on Node.js 13 or 14 you should be able to clone the repo, switch the `"type"` field in package.json, and then `import YAML from '/path/to/yaml/src/index.js'`, and that appears to work fine.

As for TS types, if those could then be extracted from TSDoc code comments in JS files, that could provide a best-of-all-worlds type solution.
