### ISSUE TITLE
Jos

### ISSUE THREAD

**Issue by inos123** [eemeli/yaml#180]
# Add project specific ProGuard rules here.
# By default, the flags in this file are appended to flags specified
# in ./Users/alexanderchiou/Library/Android/sdk/tools/proguard/proguard-android.txt
# You can edit the include path and order by changing the proguardFiles
# directive in build.gradle.
#
# For more details, see
#   http://developer.android.com/guide/developing/tools/proguard.html

# Add any project specific keep options here:

# If your project uses WebView with JS, uncomment the following
# and specify the fully qualified class name to the JavaScript interface
# class:
#-keepclassmembers class fqcn.of.javascript.interface.for.webview {
#   public *;
#}
android {
    ...
    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile(
              'proguard-android-optimize.txt'),
              // List additional ProGuard rules for the given build type here. By default,
              // Android Studio creates and includes an empty rules file for you (located
              // at the root directory of each module).
              'proguard-rules.pro'
        }
    }
    flavorDimensions "version"
    productFlavors {
        flavor1 {
          ...
        }
        flavor2 {
            proguardFile 'flavor2-rules.pro'
        }
    }
}
[agorartm.log](https://github.com/eemeli/yaml/files/4925063/agorartm.log)
  * Didesain ulang menjadi pola tunggal
  * Diimplementasikan completeCommand () berdasarkan [info perintah]
  * Perintah Tcl saveScript baru

**Comment by eemeli** [comment]
Closing as off-topic.
