### ISSUE TITLE
Quote management?

### ISSUE THREAD

**Issue by ogrotten** [eemeli/yaml#198]
I need to build a specific output: 

    - title: "May 7th"

That is to say that the key needs to be plain and the value needs to be "double quoted"

If I set up with 

	YAML.scalarOptions.str.defaultType = 'QUOTE_DOUBLE'
	YAML.scalarOptions.str.defaultKeyType = 'PLAIN'

just before `YAML.stringify()`, the output comes like

    - "title": "September 21st"

What options would I use to get the format that I need (my first example)?

**Comment by eemeli** [comment]
Could you verify that you're experiencing this with version `2.0.0-0`? `defaultKeyType` was only added in that version.

**Comment by eemeli** [comment]
Closing as presumably answered.

**Comment by ogrotten** [comment]
I apologize that I didn't make it back here.

From what I remember, I found that `yarn add` added the stable 1.x version, but the most prominent documentation on the website was 2.x. IOW, the defaults went in 2 different directions. 

Also if I recall, the redirect to 1.x documentation is a single sentence buried in the 2.0 docs. IOW it was easy to miss if scanning the docs looking for a specific single thing.

My suggestion would be to make that redirect not only more prominent, but it's own section.
