### ISSUE TITLE
Maintain the loc info from input text? (CRLF)

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#20]
version: 1.0.0-rc.7

https://github.com/eemeli/yaml/blob/c04ab2c20a8cbafe7a018901f4fd3aa7f3172470/src/cst/parse.js#L7

It's surprising that the loc info is not same as the input one when it comes to CRLF:

```js
const YAML = require("yaml").default;

const text = "a:\r\n  123\r\n";
const cst = YAML.parseCST(text);

const plain = cst[0].contents[0].items[1].node;
plain.strValue; //=> "123"

text.slice(plain.valueRange.start, plain.valueRange.end); //=> " 12"
```

**Comment by eemeli** [comment]
You're right, that is a bit surprising, and does throw off the ranges when used afterwards. Unfortunately the `\r` trimming is pretty deeply assumed by the parser, and not doing so at the start would really complicate things down the road.

Will need to think about this before implementing.
