### ISSUE TITLE
Unable to install yaml package through npm

### ISSUE THREAD

**Issue by rajaSahil** [eemeli/yaml#202]
Getting this error when I ran `npm install`
```
npm ERR! code ETARGET
npm ERR! notarget No matching version found for yaml@2.0.0.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
npm ERR! notarget 
npm ERR! notarget It was specified as a dependency of 'client'
npm ERR! notarget 
```

**Comment by eemeli** [comment]
That would be because no such version has been published yet.

**Comment by rajaSahil** [comment]
Ohh okay. So I used `"yaml" : "v2.0.0-0"` and it got resolved. Thanks.

**Comment by BCsabaEngine** [comment]
Both try "npm install yaml@next" or "npm install yaml@2.0.0-4" successfully installed the latest (today) version , but "npm outdated" displays old version. It compares with 1.x.x the latest. Why?

`Package  Current   Wanted  Latest  Location
`
`yaml     2.0.0-4  2.0.0-4  1.10.2  node_modules/yaml
`

**Comment by eemeli** [comment]
Because it's comparing to the `latest` version, which is still 1.10.2.
