### ISSUE TITLE
Consider addinng node parameter to tag resole method

### ISSUE THREAD

**Issue by KostiantynKopytov** [eemeli/yaml#206]
Basic reasons for this I'd like to have a different meaning for tagged values:

!tag 3 -> number 3
!tag '3' -> string '3'
!tag "3" -> string '3'

Originally node has this information about node type (SINGLE/DOUBLE/PLAIN) but it not in resolve method itself.

**Comment by KostiantynKopytov** [comment]
Probably example will show my intentions better.
Let's have custom tag that treats tag value as yaml:
```
const yaml = require('yaml');
const someTag = {
  tag : '!tag',
  resolve (value, onError) {
    return yaml.parse(value);
  },
  stringify (node) {
    return yaml.stringify(node);
  }
};
yaml.defaultOptions.customTags = [someTag];

console.log(JSON.stringify(yaml.parse(`!tag 3`))) // -> 3
console.log(JSON.stringify(yaml.parse(`!tag '3'`))) // -> 3
console.log(JSON.stringify(yaml.parse(`!tag "3"`))) // -> 3
console.log(JSON.stringify("3")) // -> "3"
```

But if in resolve method I had access to the Node object, or at least Node type, to treat tag value differently, I would be able to differ if it was quoted or not (or may be it could helpful in other ways).

Something like this:
```
const yaml = require('yaml');
const someTag = {
  tag : '!tag',
  resolveBy : 'node',  // 'node' | 'value' - value by default
  resolve (node, onError) {
    return yaml.parse(node);
  },
  stringify (node) {
    return yaml.stringify(node);
  }
};
yaml.defaultOptions.customTags = [someTag];
```

**Comment by eemeli** [comment]
I think I do understand the mechanics of what you're looking for, but not the _why_ of it. What is the situation in which this would be beneficial?

**Comment by KostiantynKopytov** [comment]
We keep configuration in yaml files. There're two types of configurations: templates and overrides. There's a tool that updates override yamls, it compares it and produces result that is nicely formatted and and still valid yaml. And to express differences in the configuration it uses tags, for example:

```yaml
config:
  prop1: !default 1
  prop2: !unkown 2
```

**Comment by KostiantynKopytov** [comment]
I could do it by adding another quotes - but it'll look ugly:

```yaml
config:
  prop1: !default 1
  prop2: !unknown '"2"'
  prop3: 3 # !default 5
```

**Comment by eemeli** [comment]
It seems like what you're really looking for is an annotation on the data, rather than a specifier for its type. And that's not really what tags are meant for. Is the annotation meant for human or machine consumption? If it's for humans, maybe it'd be easiest for you to add a comment on the value instead?

**Comment by KostiantynKopytov** [comment]
That's extacly that are tags for. Idea that I want to introduce a special types "default" or "unknown" and handle them specifically with custom tags, but with current "limitation" I could not do that properly.

Comments could solve problem, but leaves more space for errors and requires 2nd parsing. And also I'd want to keep comments available for regaular usage.

template:
```yaml
config:
  prop1: 123
```
override:
```yaml
config:
  prop1: 456 # !default
```

It'll require parsing overrides as a document, then finding all commented node with a specfic "tag comment", and replacing them with defaults. 
Originally I just read overrides, `!default` - will replace them with `undefined`, `config=_.merge({}, template, override)`

**Comment by eemeli** [comment]
Huh, I just realised that perhaps some miscommunication may have happened here. Please have a read through the [Writing Custom Tags](https://eemeli.org/yaml/#writing-custom-tags) section of the docs; it may be that what you're looking for is already possible. One key aspect to consider is that the AST node's `type` is only assigned after it has been resolved, so it should be available on the Nodes generated by your custom tag.

**Comment by eemeli** [comment]
Closing as presumably solved.
