### ISSUE TITLE
disable anchors in stringify

### ISSUE THREAD

**Issue by dudif91** [eemeli/yaml#211]
hi, is there a way to disable anchors such as &a1 when using stringify.

I'm using YAML version 1.10.0

tnx

**Comment by eemeli** [comment]
I'm pretty sure that using just `YAML.stringify()` that isn't possible, but this will probably do what you want:

```js
const doc = new YAML.Document()
doc.setSchema()
doc.contents = doc.schema.createNode(yourValueHere)
String(doc)
```

The reason why that works is that in v1 the automatic reference detection was a part of the `stringify` method in particular, while `createNode` didn't include it. This changes (along with some of the clumsiness of the above API) in v2, but that's an entirely different issue.

**Comment by dudif91** [comment]
tnx that was very helpful

**Comment by ushuz** [comment]
> I'm pretty sure that using just `YAML.stringify()` that isn't possible, but this will probably do what you want:

Can this be made into an option of `stringify()`?
