### ISSUE TITLE
Boolean-like strings are handled incorrectly

### ISSUE THREAD

**Issue by SimonAlling** [eemeli/yaml#212]
```javascript
import yaml from "yaml";

const original = `
foo:
  value: "no"
`;

console.log(yaml.stringify(yaml.parse(original)));
```

Output:

```
foo:
  value: no
```

(Note the missing quotation marks around `no`.)

This is problematic because [`no`means `false` in YAML](https://yaml.org/type/bool.html).

For context, my real-life use case is to augment the YAML produced during [`helm install`](https://helm.sh/docs/helm/helm_install/) in a so-called [post-renderer](https://helm.sh/docs/topics/advanced/#post-rendering), but this doesn't work because `value: "no"` is changed to `value: no`, causing this error in Kubernetes:

```
Error: Deployment in version "v1" cannot be handled as a Deployment: […] ReadString: expects " or n, but found f, error found in #10 byte of ...|,"value":false},{"na|...` […]
```

The inverse problem seems to be present too:

```javascript
console.log(yaml.parse(`
foo:
  value: false
`));
// { foo: { value: false } }

console.log(yaml.parse(`
foo:
  value: no
`));
// { foo: { value: 'no' } }
```

**Comment by eemeli** [comment]
The page you linked to is "Boolean Language-Independent Type for YAML™ Version 1.1"

`yaml` defaults to using the "core" schema of the 1.2 version of the spec, which does not consider `no` as a valid representation of a false value. If you'd like to follow the 1.1 spec version or its schema, use an appropriate option: https://eemeli.org/yaml/#options

**Comment by SimonAlling** [comment]
Oh, I didn't realize. Thanks for the explanation!
