### ISSUE TITLE
TypeScript definition should use unions type over base type

### ISSUE THREAD

**Issue by joshuaavalon** [eemeli/yaml#221]
**Describe the bug**
After you parse an document, you cannot narrow down the return type but check `type`.

**To Reproduce**
```typescript
const doc = yaml.parseDocument(str);
const { type } = doc.contents || {};
if (doc.contents?.type === Type.MAP) {
    // doc.contents is detected as Node
}
```

**Expected behaviour**
```typescript
const doc = yaml.parseDocument(str);
const { type } = doc.contents || {};
if (doc.contents?.type === Type.MAP) {
    // doc.contents is detected as BlockMap
}
```

**Versions (please complete the following information):**
 - Environment: Node.js 14
 - `yaml`: 1.10.0 or 2.0.0-1

**Additional context**
This can be fixed by replacing type of `Parsed.contents` to union type.
```typescript
type AllNodeType = AST.FlowMap | AST.BlockMap; // Union of all possible types
interface Parsed extends Document {
  contents: AllNodeType | null
  /** The schema used with the document. */
  schema: Schema
 }
```

This is work as long as `type` is not duplicated. This is pretty common in TypeScript. You can read more at [the official document](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions).

**Comment by eemeli** [comment]
A PR for this would be welcome. The same issue is probably repeated in other parts of the library as well. With #203 I'm starting to introduce more TS code into the source of `yaml`, but there isn't a schedule for if/when that might extend to replacing all of the current JS codebase, which necessitates these hand-crafted d.ts files.

**Comment by eemeli** [comment]
@joshuaavalon I specified the parsed content type a bit, to `Scalar | YAMLMap | YAMLSeq | null`. Is that enough for your purposes, or were you doing something even more specific?

**Comment by joshuaavalon** [comment]
@eemeli If you use the base type (i.e. `YAMLMap`) instead of the implementation type (i.e. `FlowMap`), TypeScript can only detected it as `YAMLMap`. It is better to create a type that contain all implementation types.

```typescript
type Scalars = BlockFolded | BlockLiteral  | PlainValue | QuoteDouble | QuoteSingle;
type Maps = FlowMap | BlockMap;
type Seqs = FlowSeq | BlockSeq;

type AllNodeTypes = Scalars | Maps | Seqs;
```

From TypeScript compiler, it you don't state the implementation types, it does not know what is the possible types.

If you want to support custom nodes better, you can even use generics:

```typescript
interface Parsed<T extends AllNodeTypes = AllNodeTypes> extends Document {
  contents: T | null
  schema: Schema
 }
```

This will allows users to add their custom types.

**Comment by eemeli** [comment]
Ah, but there's the rub; at this level, `Scalar`, `YAMLMap` and `YAMLSeq` _are_ the implementation types. The last of those, for instance, is internally constructed by calling `new YAMLSeq()` for both flow & block sequences. It's also perfectly fine to switch the `type` of a node within its supported range, so e.g. this works:

```js
const doc = YAML.parseDocument('- one\n- two\n')
doc.contents.type = 'FLOW_SEQ'
String(doc) === '[ one, two ]\n'
```

**Comment by joshuaavalon** [comment]
I still think using implementation type is better. Since that use case is not documented, there is no need to expose internal api. If others want to use internal api, they can cast the type themselves.

**Comment by eemeli** [comment]
The perhaps the documentation ought to be improved to make it even clearer, as the behaviour of the stringifier is documented e.g. here: https://eemeli.org/yaml/#collections

And, as I mentioned before, in the AST, `Scalar`, `YAMLMap` and `YAMLSeq` are the actual implementations of the nodes. In the source JS code there are not different `Node` descendants for e.g. flow & block sequences, just the one `YAMLSeq`. This is what the TS typings are intended to convey.

**Comment by eemeli** [comment]
The docs now mention `type` modifications more explicitly: https://eemeli.org/yaml/#modifying-nodes
