### ISSUE TITLE
Typescript type definitions missing some CST.Node members

### ISSUE THREAD

**Issue by 1nVitr0** [eemeli/yaml#222]
**Describe the bug**
Some of the functions implemented in the class CST.Node are not reflected in it's type definition.

**To Reproduce**
Try to access a CST Node's `rangeAsLinePos` member in a typescript project.

**Expected behaviour**
The CST Node includes all of the relevant members and methods in it's type definition

**Versions (please complete the following information):**
 - Environment: Node 15.6.0
 - `yaml`: 1.10.0 (but the current master branch does not seem to fix the problem)

**Additional context**

If I didn't miss some automatic type generating script, the fault lies in parse-cst.d.ts. CST.Node only export the following members:

```
interface Node {
    context: ParseContext | null
    error: YAMLSyntaxError | null
    range: Range | null
    valueRange: Range | null
    props: Range[]
    type: Type
    value: string | null

    readonly anchor: string | null
    readonly comment: string | null
    readonly hasComment: boolean
    readonly hasProps: boolean
    readonly jsonLike: boolean
    readonly rawValue: string | null
    readonly tag:
      | null
      | { verbatim: string }
      | { handle: string; suffix: string }
    readonly valueRangeContainsNewline: boolean
 }
```

while the implementation of CST.Node in src/cst/Node.js clearly has more methods / members. Grossly oversimplifying, the members / methods:

```
interface Node {
        context: any;
        error: any
        range: any;
        valueRange: any
        props: any[];
        type: any;
        value: any
	getPropValue(idx, key, skipKey): any;
	anchor: any;
	comment: any;
	hasComment: boolean;
	hasProps: boolean;
	includeTrainlingLines: boolean;
	jsonLike: boolean;
	rangeAsLinePos: { start: any, end: any };
	rawValue: string;
	tag: { handle: any, suffix: any }
	valueRangeContainsNewline: boolean;
	commentHasRequiredWhitespace(start): boolean;
	parseComment(start): any;
	setOrigRanges(cr, offset): any;
}
```

So the missing members / methods are:

- `getPropValue(idx, key, skipKey): any;`
- `includeTrainlingLines: boolean;`
- `rangeAsLinePos: { start: any, end: any };`
- `commentHasRequiredWhitespace(start): boolean;`
- `parseComment(start): any;`
- `setOrigRanges(cr, offset): any;`

Obviously the types here are incorrect, I'd have to go into the code more to provide matching types.

I am happy to dive in a bit deeper and submit a pull request, but maybe some of these are private and left out on purpose. Especially the method `rangeAsLinePos` is what I am most interested in.

**Comment by eemeli** [comment]
The CST is getting completely refactored in #203, so it's probably not worthwhile to update/include all these types of the current implementation. I'll add in `rangeAsLinePos` to the next beta though, if/as you've a need for it, and it's mentioned in the documented API.

As the current typings are manually maintained, I left out the internal stuff that I figured wouldn't be of interest outside the library itself.
