### ISSUE TITLE
YAML validation method

### ISSUE THREAD

**Issue by stcalica** [eemeli/yaml#226]
For YAML validation I have to do a classic try/catch. 
But it would be cool if we can have a validator that returned a true or false if the YAML is valid.

**Comment by eemeli** [comment]
Something like that is already available via `parseDocument`, but maybe the docs are not clear enough for this use case?

```js
const doc = YAML.parseDocument(src)
if (doc.errors.length === 0) console.log('src is valid YAML')
```

**Comment by stcalica** [comment]
@eemeli interesting and can YAML.parseDocuments read from memory? it does not have to be a binary file -- src can be an object not a filepath?

**Comment by eemeli** [comment]
With the current API, `src` is expected to be a `string`. Once #203 gets merged, there'll be an API also supporting Node.js streams.

**Comment by eemeli** [comment]
Had a read-through of my own docs, and essentially the place where I would've added a clearer mention about this already has that: https://eemeli.org/yaml/#parsing-documents
