### ISSUE TITLE
TypeScript Type declarations

### ISSUE THREAD

**Issue by ColinBradley** [eemeli/yaml#23]
TypeScript definition files or something in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped) would be great. Do you have any plans for them?

I may create some definition files myself on DefinitelyTyped - as I would really like to use this package. Unless you have any objections? It would probably only be basic though.

Great package and great work on the documentation by the way! :)

**Comment by ikatyang** [comment]
I've written some of them [here](https://github.com/ikatyang/yaml-unist-parser/blob/master/types/yaml/index.d.ts), I'm still waiting for stable release to finish the types and send to DT.

**Comment by ColinBradley** [comment]
I've updated your implementation, @ikatyang. You can find it in this [gist](https://gist.github.com/ColinBradley/2109d049b6ff1ed00ea96e5944d92acd). There are still a few holes and it could do with being fully modularized into different files before going into DT, but it works for me! If I have some more time, I will try to get it into DT, but feel free to pick it up (or anyone else).

**Comment by ikatyang** [comment]
Updated the updated implementation [here](https://github.com/ikatyang/yaml-unist-parser/blob/d928df79e5767b3db4d8fd6f8c58aa87f480fef8/types/yaml/index.d.ts) 😉, this should be all the types. I think sending PRs to DT before stable release is dangerous, there might be breaking changes which is not good for type consumers. (Actually, there's already one -> #25)

**Comment by eemeli** [comment]
@ikatyang That does look almost complete. It's still missing the `yaml/scalar`, `yaml/types/binary` and `yaml/types/timestamp` exports, but that might be it. Plus of course the changes from at least #25, once I get a release together that includes that.

**Comment by eemeli** [comment]
@ikatyang Now that the 1.0.0 release is out, the TS definitions could probably be released as well?

**Comment by eemeli** [comment]
Closing this as the definitions have now been merged to the DT master.
