### ISSUE TITLE
Invalid Yaml produced when using objects with undefined values

### ISSUE THREAD

**Issue by vkbansal** [eemeli/yaml#239]
**Describe the bug**

**To Reproduce**
```
const yaml = require('yaml')
console.log(yaml.stringify({ a: { b: undefined }})) 
```
this outputs

```
a:
  ? b
```

**Expected behaviour**
```
a:
  b: null
```

**Versions:**

- Environment: Node.js 14.16.0
- `yaml`: 1.10.0

**Comment by vkbansal** [comment]
Thanks for responding. Great to hear that this is fixed in v2.

The issue is that our backend systems are in JAVA and it cannot parse such YAML.

I'll have to wait for a stable v2 release before upgrading. 

For now I have put in a temporary workaround `YAML.stringify(JSON.parse(JSON.stringify({...})))`. It might not seem like a good solution but it gets the job done.

**Comment by eemeli** [comment]
Actually, you can get the output that you want also in 1.1.0 using the `simpleKeys` option:
```js
YAML.stringify( { a: { b: undefined } }, { simpleKeys: true })
// "a:\n  b: null\n"
```

**Comment by vkbansal** [comment]
Ok I will try this and update. Thanks for the help.
