### ISSUE TITLE
TypeScript project build fails in 2.0.0-4

### ISSUE THREAD

**Issue by perspectivus1** [eemeli/yaml#245]
**Describe the bug**
When I try to build a TypeScript project that depends on ymal@2.0.0-4, I get the following error messages:
```
'commentBefore' is defined as a property in class 'NodeBase', but is overridden here in 'Pair<K, V>' as an accessor.
'spaceBefore' is defined as a property in class 'NodeBase', but is overridden here in 'Pair<K, V>' as an accessor.
```

for file `node_modules/yaml/dist/nodes/Pair.d.ts`.

**To Reproduce**
* Create a TypeScript project
* `npm i yaml@2.0.0-4`
* Build the project

**Expected behaviour**
Project build should succeed

**Versions (please complete the following information):**

- `yaml`: 2.0.0-4
-  Node.js: 14.6.0

**Additional context**
The original source code has these comments before the problematic lines:
```
// @ts-ignore This is fine.
```
[Pair.ts#L90](https://github.com/eemeli/yaml/blob/v2.0.0-4/src/nodes/Pair.ts#L90)

But these lines disappear in the resulting `d.ts` file.

**Comment by eemeli** [comment]
Ach, I need to figure out how to run a check also on the generated type definitions; I had not expected for the `@ts-ignore` to get dropped. Also need to figure out how to resolve this in the first place.

**Comment by eemeli** [comment]
Found instructions in microsoft/TypeScript#33509 for a more suitable workaround that should have the same behaviour, but not require any `@ts-ignore` comments.

**Comment by Half-Shot** [comment]
Hiya, apologies for necroposting but do you know when we can expect a release to fix this? I'm currently a bit stuck as I'm unsure which version to depend on to allow my code to compile?

**Comment by eemeli** [comment]
A day or two.
