### ISSUE TITLE
In correct range

### ISSUE THREAD

**Issue by gorkem** [eemeli/yaml#258]
**Describe the bug**
The range for node corresponding to the end of a text is in correct and spans till the end of the text. 

**To Reproduce**
Using the text  `"definitions:\n  link:\n    type: string\ntype: object\nproperties:\n  uri:\n    $ref: '#/definitions/link'   \n"` I see that the range of single quote string of `#/definitions/link` extends to the whitespace while value is correct

**Expected behaviour**
The range of the string node not to go beyond

**Versions (please complete the following information):**
_next_ on vscode

**Comment by eemeli** [comment]
This is currently working as intended, i.e. such that trailing whitespace & comments are included in flow node ranges. In other words, the range of the collection in `'{ foo } #c1 \n#c2\n'` will include everything up to the first newline.

However, that intent is probably buggy, or at least sub-optimal. It's already the case that some content (full-line comments, collection item indicators) are left out of node ranges, and the block node ranges already end at the end of content.

So it would probably be least surprising to a user if the `range` behaved as you expected it to.
