### ISSUE TITLE
Incorrect int parsing

### ISSUE THREAD

**Issue by nborko** [eemeli/yaml#276]
The following YAML:

```yaml
number: 01_234
```

Should parse to  `{ number: 1234 }`, but instead parses to `{ number: '01_234' }`

According to https://yaml.org/type/int.html:

    Any “_” characters in the number are ignored, allowing a readable representation of large values.

The reverse is also true, i.e. `{ number: '01_234' }` dumps as:

```yaml
number: 01_234
```

Which is consistent behavior, but wrong YAML.

thanks!

**Comment by eemeli** [comment]
Please note the title of the page you linked to:
> Integer Language-Independent Type for YAML™ Version 1.1

That `!!int` definition is for YAML 1.1, and this library defaults to YAML 1.2, which has a much stricter definition. To parse input as YAML 1.1, use the `yaml: '1.1'` option.

**Comment by nborko** [comment]
The spec appears in https://github.com/yaml/yaml-spec/tree/main/1.2 but the YAML test suite doesn't seem to parse it that way, either. So I expect you're doing it correctly. Parsing as 1.1 is wholly undesirable.

Looks like a couple of libraries (most notably js-yaml that claims core schema support) aren't parsing correctly, so I'll just ditch them for something that is consistent.

thanks!
