### ISSUE TITLE
Document.toString result is different from the input document

### ISSUE THREAD

**Issue by douglasmuraoka** [eemeli/yaml#28]
I have an application that needs to manipulate the YAML document, add / remove some entries, and then render the new document back again to a file, keeping all the comments. The problem is, when the rendering finishes, the final product is removing the linebreaks and changing the comments scope.

Reproducer:
```
const doc = yaml.parseDocument(
  '# This comment is ok\n' +
  'entryA:\n' +
  '  - foo\n' +
  '\n' +
  'entryB:\n' +
  '  - bar # bar comment\n' +
  '\n' +
  '# Ending comment\n'
)
console.log(doc.toString())
```
Result:
```
# This comment is ok
entryA:
  - foo
entryB:
  - bar # bar comment # Ending comment
```

When I add a second ending comment, the behavior changes:
```
doc = yaml.parseDocument(
  '# This comment is ok\n' +
  'entryA:\n' +
  '  - foo\n' +
  '\n' +
  'entryB:\n' +
  '  - bar # bar comment\n' +
  '\n' +
  '# Ending comment\n' +
  '# Ending comment 2\n'
);
console.log(doc.toString())
```

Result:
```
# This comment is ok
entryA:
  - foo
entryB:
  - bar # bar comment
  # Ending comment
  # Ending comment 2
```

The identation of the comments is important for me, because I am giving my users some instructions of how to configure their application using the YAML file. So if my comments end up in the wrong scope, my users will think that their input should be done in that scope, which will be wrong.
Is there a way to maintain the scope of my comments and avoid the linebreaks removal?

I was expecting this:
```
# This comment is ok
entryA:
  - foo

entryB:
  - bar # bar comment

# Ending comment
# Ending comment 2
```

**Comment by eemeli** [comment]
I think there are three things happening (wrong) here:

- [ ] the `# bar comment # Ending comment` bit is definitely a bug, which ought to be relatively easy to fix,
- [ ] the indentation level should be taken into account when choosing which node to attach the end comments to, and
- [ ] keeping empty lines is a missing feature.

So at this moment `yaml` doesn't quite provide a solution for what you want, but those things are now on my to-do list.

**Comment by eemeli** [comment]
I'm closing this in favour of #41 and #42, so that those separate issues can be tracked separately.
