### ISSUE TITLE
Circular dependency error with rollup for browser

### ISSUE THREAD

**Issue by jdesrosiers** [eemeli/yaml#291]
**Describe the bug**
When bundling `yaml` for the browser using rollup, I get a circular dependency error. This seems to be a quirk (maybe even a bug?) of the way rollup builds for the browser. A small tweak seems to solve the problem.

Change this,
```javascript
import * as YAML from './dist/index.js'
```
to this,
```javascript
import * as YAML from '../browser/dist/index.js'
```

**To Reproduce**
Here's a minimal reproduction.

_package.json_
```json
{
  "scripts": {
    "build": "rollup -c"
  },
  "dependencies": {
    "@rollup/plugin-commonjs": "^19.0.0",
    "@rollup/plugin-node-resolve": "^13.0.0",
    "rollup": "^2.52.4",
    "yaml": "^2.0.0-6"
  }
}
```
_rollup.config.js_
```javascript
const { nodeResolve } = require("@rollup/plugin-node-resolve");
const commonjs = require("@rollup/plugin-commonjs");


module.exports = {
  input: "index.js",
  output: {
    format: "iife",
    file: "dist.js",
    name: "Test",
    exports: "auto"
  },
  plugins: [
    nodeResolve({
      browser: true
    }),
    commonjs(),
  ]
};
```
_index.js_
```javascript
const YAML = require("yaml");
  
const data = YAML.parse(`foo: bar`);
console.log(data);
```

Run rollup with `npm run build`. You should see the circular dependency error. Make the change suggested above (or a better one if it exists) and the error goes away and you can run the bundled app with `node dist.js`.

**Comment by eemeli** [comment]
Huh, this looks like it's actually a bug in `@rollup/plugin-node-resolve`.

When its `browser: true` option is enabled, the package.json `"browser"` field is considered during resolution, and for `yaml` it includes the mapping
```
"./dist/index.js": "./browser/index.js"
```
which according to [the spec](https://github.com/defunctzombie/package-browser-field-spec) should mean that just `yaml/dist/index.js` is resolved as `yaml/browser/index.js`. However, that file itself includes a dependency `"./dist/index.js"`, which _should_ resolve as `yaml/browser/dist/index.js` but happens to be an exact string match to the mapped dependency from the package root, and therefore produces the weird circular dependency
```
node_modules/yaml/browser/index.js -> node_modules/yaml/browser/index.js
```

I'll file a bug about this there. In the meantime, for `yaml` the easiest fix would be to leave out the `browser: true` setting, as its export map is already set up to have Rollup use the `yaml/browser/...` files as they're the "default" export ("node" is special-cased). This won't help of course with projects that need said option for other dependencies.

**Comment by eemeli** [comment]
Closing in favour of the upstream bug rollup/plugins#919.
