### ISSUE TITLE
Error loading in Deno

### ISSUE THREAD

**Issue by justinmchase** [eemeli/yaml#301]
**Describe the bug**
```ts
error: Import 'https://deno.land/x/yaml@v2.0.0-7/src/nodes/Scalar.js' failed: 404 Not Found
    at https://deno.land/x/yaml@v2.0.0-7/src/index.ts:22:0
```

**To Reproduce**
Steps to reproduce the behaviour.
1. Install Deno
2. Run `deno eval "export * as YAML from 'https://deno.land/x/yaml@v2.0.0-7/src/index.ts'"`

**Expected behaviour**
I expect the module to be loaded successfully, no errors

**Versions (please complete the following information):**

- Environment: 
```
deno --version
deno 1.13.0 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```
- `yaml`: `v2.0.0-7`

**Additional context**
Full stack:
```
deno eval "export * as YAML from 'https://deno.land/x/yaml@v2.0.0-7/src/index.ts'"
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLSeq.js
Download https://deno.land/x/yaml@v2.0.0-7/src/doc/Document.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/lexer.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/tags
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/parser.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Alias.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Node.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Scalar.js
Download https://deno.land/x/yaml@v2.0.0-7/src/errors.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/Pair.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/cst.js
Download https://deno.land/x/yaml@v2.0.0-7/src/visit.js
Download https://deno.land/x/yaml@v2.0.0-7/src/parse/line-counter.js
Download https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLMap.js
Download https://deno.land/x/yaml@v2.0.0-7/src/public-api.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/types
Download https://deno.land/x/yaml@v2.0.0-7/src/options.js
Download https://deno.land/x/yaml@v2.0.0-7/src/compose/composer.js
Download https://deno.land/x/yaml@v2.0.0-7/src/schema/Schema.js
error: Import 'https://deno.land/x/yaml@v2.0.0-7/src/nodes/YAMLSeq.js' failed: 404 Not Found
    at https://deno.land/x/yaml@v2.0.0-7/src/index.ts:24:0
```

The files of course are all typescript in the repository and it fails trying to download them because in the code they're all referencing each other as `.js`. I believe in node it works because its running all the transpiled files after typescript gets them but in Deno that transformation is transparent and it requires the references to be correct.

I know there are a couple of ways to solve this, such as using some auto-esm transpiler, or perhaps you have the JS version published somewhere that I'm not seeing... but I didn't see any documentation in your readme on the way you're intending it to be supported so I thought I'd ask here.

**Comment by eemeli** [comment]
It seems s bit surprising that this would fail in Deno, given the TypeScript itself is fine with resolving `.js` into `.ts`. I don't use Deno myself, so if there's a simple fix for this I'd be interested. The sources _should_ be pretty Deno-compatible, and I'd really rather avoid adding a separate build for it.

**Comment by justinmchase** [comment]
Since I had to re-read this and figure it out again, I just want to leave a note here about the actual solution. Perhaps something like below would be a nice addition to the main readme?


### ESM

Its possible to load `yaml` using EcmaScript Module loading in Deno by importing through [esm.js](https://esm.js)

```ts
export * as yaml from 'https://esm.sh/yaml@2.1.1';
```

**Comment by justinmchase** [comment]
Or actually pulling from esm.sh seems to have problems with the latest version of Deno so an alternative is this:

```ts
import {
  parse,
  stringify,
} from "https://deno.land/std@0.152.0/encoding/yaml.ts";
export const YAML = { parse, stringify };
```

**Comment by jcayzac** [comment]
@justinmchase that's not the same library.

This works just fine in Deno:

```ts
import YAML from 'https://esm.sh/yaml@2.1.3'
const { parse, stringify } = YAML
```

**Comment by jeff-hykin** [comment]
While ESM works, the module published on deno.land/x does not:

```js
import Yaml from  "https://deno.land/x/yaml@v2.4.3/src/index.ts"
> Uncaught TypeError: Module not found "https://deno.land/x/yaml@v2.4.3/src/compose/composer.js".
    at https://deno.land/x/yaml@v2.4.3/src/index.ts:1:26
    at async <anonymous>:1:50
```

(It should be looking for `"https://deno.land/x/yaml@v2.4.3/src/compose/composer.ts"` but looks for js instead)

**Comment by jcayzac** [comment]
```js
import * as yaml from 'npm:yaml'
```

**Comment by jeff-hykin** [comment]
Okay, If that's the official usage then you might want to remove the deno module since its broken

**Comment by justinmchase** [comment]
I would agree with the previous comment, what's published to deno.land/x I would expect to work with Deno as a Deno compatible module.

**Comment by eemeli** [comment]
PRs welcome for adding a separate Deno endpoint and build that renames the imports and adds tests verifying that the result works in Deno.

**Comment by eemeli** [comment]
> * I had to mark whether something was a type export or a normal export
> * needed to prefix node builtins with "node:"
> * needed to add `import process from "node:process"` instead of using the global `process` var

These sound like changes that could/should at least in part be applied directly to the source, rather than layered on for Deno specifically. As in, please file a separate PR for these.

> * needed to change the "from 'yaml'" of the tests to actually import from the relative path

Is Jest not used as the test runner for the proposed Deno build? At least in Node.js, it's [handling](https://github.com/eemeli/yaml/blob/main/config/jest.config.js) the path rewrites for the test imports.

**Comment by jeff-hykin** [comment]
> These sound like changes that could/should at least in part be applied directly to the source, rather than layered on for Deno specifically.

Great! Thats exactly what I was hoping to get some feedback on. 

> Is Jest not used as the test runner for the proposed Deno build?

Yeah, I have no idea how this works. Both I didnt realize that was a feature of Jest, and I'm not sure how that Jest feature ends up interacting with Deno. Thanks for that link. Whenever I look at this again, that will help me figure out what's going on.
