### ISSUE TITLE
keepCstNodes was useful; consider restoring it

### ISSUE THREAD

**Issue by andersk** [eemeli/yaml#308]
**Is your feature request related to a problem? Please describe.**

In 2.0.0-3, I could use the high-level `Node` API with `keepCstNodes` to easily inspect the document and select part of it to edit, then use the low-level `CST` API to edit that part and re-serialize the document without making unnecessary formatting changes to the other parts. However, in 2.0.0-4, the `keepCstNodes` option was removed, so this is no longer possible.

```js
import { parseDocument } from "yaml";

const yaml = `\
a: b
c:
    d: [e, f, g]
    h:
        {
            i: j,
            k: l,
        }
    m: n
o: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
`;

const doc = parseDocument(yaml, { keepCstNodes: true });
doc.contents.get("c").get("m", true).cstNode.value = "edited";
console.log(doc.cstNode.toString());

/*
a: b
c:
    d: [e, f, g]
    h:
        {
            i: j,
            k: l,
        }
    m: edited
o: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
*/
```

**Describe the solution you'd like**

Restore the `keepCstNodes` option.

**Describe alternatives you've considered**

* Both `doc.toString()` and `stringify(doc)` make formatting changes to unrelated parts of the document.

  ```js
  doc.contents.get("c").set("m", "edited");
  console.log(doc.toString());

  /*
  a: b
  c:
    d: [ e, f, g ]
    h: { i: j, k: l }
    m: edited
  o: Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod
    tempor incididunt ut labore et dolore magna aliqua.
  */
  ```

* I could use `Parser.parse` and do the entire process using `CST` from start to finish, but that would require much more code for locating the part of the document I want to edit.

* I could use both `parseDocument` and `Parser.parse` and use techniques like the [`findScalarAtOffset` example](https://eemeli.org/yaml/#cst-stringify-cst-token-collectionitem-string) in the documentation to correspond AST nodes to CST nodes, but that would also require much more code.

**Comment by eemeli** [comment]
Okay, that use case is entirely valid and should be supported. I added #309 for this, but I'm not sure if that's the right choice. As I mention there, that approch _mostly_ works, but has some corner cases that aren't much fun.

One possible alternative would be adding a utility function like this:

```ts
import { CST } from 'yaml'

function findItem (
  cst: Document | CollectionItem,
  path: (string | number)[]
) {
  let item: CST.CollectionItem | undefined = cst
  for (const key of path) {
    if (!item || !CST.isCollection(item.value)) return undefined
    if (typeof key === 'number') item = item.value.items[key]
    else {
      item = item.value.items.find(
        it => CST.isScalar(it.key) && CST.resolveAsScalar(it.key).value === key
      )
    }
  }
  return item
}
```

That could then be used with your example code like this:

```js
import { CST, Parser } from 'yaml'

const yaml = ...
const cst = Array.from(new Parser().parse(yaml))
const token = findItem(cst[0], ['c', 'm']).value
CST.setScalarValue(token, 'edited')

cst.map(CST.stringify).join('')
```

I'm undecided about whether to add one or both of these interfaces to the library. Thoughts?

**Comment by andersk** [comment]
If we want to make the `CST` API as capable as the `Node` API, I think there’s a lot of functionality that would need to be added. For example, that `findItem` implementation gives the wrong result on this case:

```yaml
true: a
"true": b
```

because only the `Node` API knows which plain tokens should really be parsed as strings rather than some other type. This particular case might be rare because YAML is usually used in a JSON-compatible way—but the same API gap might come up in other ways (e.g. in some list of maps, I want to increment the number value at key `foo` in every map where the boolean value at key `bar` is true).

Another API gap that might be important in some cases is alias node resolution.

The `keepSourceTokens` approach might have its trip hazards, but it seems like a simple way to enable a range of uses that aren’t currently possible, so I think it’s worthwhile.

**Comment by eemeli** [comment]
Achieving feature parity between the CST and Document/Node APIs is not a design goal. People want to do all sorts of things with YAML, and the intent with `yaml` is to make those things possible with the most user-friendly API.

At the CST level of processing, there is no concept of schema, i.e. the mapping that YAML uses to determine that a plain scalar `true` ought to be considered to have a boolean value. Instead, all scalar values are strings. If you're really working with a data structure that may mix boolean and string keys, then you do need the schema to disambiguate them and need to work in the Document world. I would, however, challenge that this issue actually shows up much in the real world.

**Comment by reimund** [comment]
We are using `keepCstNodes` to get nice contextual error messages for our yaml based processing engine. Each processing class has a reference to the underlying `Node`. Now, using `keepCstNodes` that's all we need to figure out the source yaml and using that we can construct a useful error message inserted on the relevant line of the yaml source.

Not sure how to do that now when `cstNode` is removed.

```yaml
item: An example
   process: Foobar
   input: [my_var1, my_var2]  <-- Error resolving my_var1
```

**Comment by eemeli** [comment]
@reimund Have you looked yet at the error output of `yaml@2`? It might already provide everything that you need:
```js
YAML.parse(`\
item:
   process: Foobar
   input: [@my_var1, my_var2]
`)
```
```
YAMLParseError: Plain value cannot start with reserved character @ at line 3, column 12:

   input: [@my_var1, my_var2]
           ^

    at Composer.onError (/Users/eemeli/code/yaml/dist/compose/composer.js:71:34)
    at _onError (/Users/eemeli/code/yaml/dist/compose/resolve-flow-scalar.js:10:42)
    at plainValue (/Users/eemeli/code/yaml/dist/compose/resolve-flow-scalar.js:68:9)
    [...] {
  code: 'BAD_SCALAR_START',
  pos: [ 36, 37 ],
  linePos: [ { line: 3, col: 12 }, { line: 3, col: 13 } ]
}
```

**Comment by reimund** [comment]
@eemeli I’m not 100% sure I understand what you mean.

To be clear, we are not checking for syntax errors in yaml but rather errors due how the user defined their processing so that our processing engine can do its job. Surely the yaml module knows nothing about how our engine works and cannot give errors about that.

But perhaps you are suggesting that we inject syntax error in the yaml in order to get the ‘linePos’ from the error message?

**Comment by eemeli** [comment]
Aaah, I'd misunderstood. So you're associating errors outside of the YAML parsing on specific nodes, yes? And then getting their source ranges so that you can build pretty errors for the user? If this is so, then something like this may be of interest:

```js
import { LineCounter, parseDocument } from 'yaml'

const src = `item:
   process: Foobar
   input: [my_var1, my_var2]
`

const lineCounter = new LineCounter()
const doc = parseDocument(src, { lineCounter })

const node = doc.getIn(['item', 'input', 0], true)
assert.equal(node.value, 'my_var1')

lineCounter.linePos(node.range[0]) // { line: 3, col: 12 }
lineCounter.linePos(node.range[1]) // { line: 3, col: 19 }
```

**Comment by reimund** [comment]
@eemeli Looks like all I needed was the `range` property of the `Node`. I didn't realize it was there all along. Thanks!
