### ISSUE TITLE
Map keys must be unique; "<<" is repeated - trouble parsing Merge Key Language-Independent Type for YAML version 1.1

### ISSUE THREAD

**Issue by jobinkavalam** [eemeli/yaml#310]
**Describe the bug**

Use of "destructuring" like syntax is sometimes found in yaml files. However, it seems to be causing problems in certain cases.

**To Reproduce**

```js
// version 1.10 (also seems to affecting 2.x)
const YAML = require("yaml");

const y = YAML.parseDocument(`
physical: &physical
    color: Golden
    malleable: yes

chemical: &chemical
    reactive: no

gold:
    <<: *physical
    <<: *chemical
`);

console.log(y.errors);
console.log(y.toString());
```

Gives error:
```
[
  YAMLSemanticError: Map keys must be unique; "<<" is repeated

.../node_modules/yaml/dist/Document-9b4560a1.js:676
    if (this.errors.length > 0) throw new Error('Document with errors cannot be stringified');
                                ^
Error: Document with errors cannot be stringified
```

**Expected behaviour**

The parsing works. Problem is when stringifying.

As a result, only analysis use cases are possible now.

In cases where one wants to use the library to transform/modify and then serialise back to JSON, there is no luck.

So, ask is if it's possible to stringifying without hitting the error.

**Versions:**

- Environment: Node.js 14.14.0 
- `yaml`: 1.10 (think also affects 2.x)

**Additional context**
https://stackoverflow.com/a/41065222

**Comment by jobinkavalam** [comment]
Found a fix ! 🎉 

In Version 2.x it's possible to set `uniqueKeys: false`

https://eemeli.org/yaml/#options

Following code works without errors:

```js
const YAML = require("yaml");

const y = YAML.parseDocument(
  `
physical: &physical
    color: Golden
    malleable: yes

chemical: &chemical
    reactive: no

gold:
    <<: *physical
    <<: *chemical
`,
  {
    uniqueKeys: false,
  }
);

console.log(y.errors);
console.log(y.toString());
```

**Comment by eemeli** [comment]
`yaml` defaults to following the 1.2 version of the YAML spec and using its core schema. That does not include support for the `<<` merge key, which is a YAML 1.1 only feature.

To enable support, either specify the version with `version: '1.1'` or explicitly enable merge keys with `merge: true`.

**Comment by eemeli** [comment]
Closing as answered.
