### ISSUE TITLE
YAML parser should fail when provided \/

### ISSUE THREAD

**Issue by teodora-sandu** [eemeli/yaml#314]
**Describe the bug**
`\/` should not be considered valid YAML, based on https://metacpan.org/pod/JSON::XS#JSON-and-YAML. This library doesn't fail on the following input:
```
foo: "\/"
```

But a different parser like https://github.com/ghodss/yaml will fail.

**To Reproduce**
Run the following script:
```
const YAML = require('yaml');

const fileContent = `
foo: "\/"`;
console.log(YAML.parseAllDocuments(fileContent));
```

The output is:
```
[
  Document {
    anchors: Anchors { map: [Object: null prototype] {}, prefix: 'a' },
    commentBefore: null,
    comment: null,
    contents: YAMLMap {
      items: [Array],
      schema: undefined,
      range: [Array],
      type: 'MAP',
      spaceBefore: true
    },
    directivesEndMarker: null,
    errors: [],
    options: {
      anchorPrefix: 'a',
      customTags: null,
      indent: 2,
      indentSeq: true,
      keepCstNodes: false,
      keepNodeTypes: true,
      keepBlobsInJSON: true,
      mapAsMap: false,
      maxAliasCount: 100,
      prettyErrors: false,
      simpleKeys: false,
      version: '1.2'
    },
    schema: Schema {
      merge: false,
      name: 'core',
      sortMapEntries: null,
      tags: [Array]
    },
    tagPrefixes: [],
    version: null,
    warnings: [],
    type: 'DOCUMENT',
    range: [ 1, 9 ]
  }
]
```

If we run the Golang equivalent:
```
package main

import (
	"fmt"
	"log"

	yaml "gopkg.in/yaml.v3"
)

var data = `
foo: "\/"
`

func main() {

	m := make(map[interface{}]interface{})

	err := yaml.Unmarshal([]byte(data), &m)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- m:\n%v\n\n", m)

	d, err := yaml.Marshal(&m)
	if err != nil {
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- m dump:\n%s\n\n", string(d))
}
```

We get:
```
error: yaml: line 2: found unknown escape character
```

**Expected behaviour**
The expected behaviour is for a warning to be included in the result so that consumers of the library can decide whether they want to support this or not.

**Versions :**

- Environment: Node.js 14.16.0
- `yaml`: 1.10.0

**Comment by eemeli** [comment]
This looks like a mismatch between YAML 1.1 and 1.2, as `"\/"` is valid in YAML 1.2, but not in YAML 1.1. It's also valid JSON.

Is there a particular use case for throwing this error? The source you cite appears to be somewhat out of date in its representation of YAML.

**Comment by teodora-sandu** [comment]
Hi @eemeli, I didn't realise `\/` was valid in YAML 1.2 as I couldn't find it anywhere. The page I linked claims YAML 1.2 is still not compatible with JSON and doesn't clarify on `\/` so that's what I was working off. Are you able to point me to the documentation that states `\/` is valid in YAML 1.2?

**Comment by eemeli** [comment]
The proper source of truth here is the YAML spec: https://yaml.org/spec/1.2/spec.html

More specifically, in section 5.7. Escaped Characters, the following rules are defined:

```
[53] ns-esc-slash ::= “/”
[62] c-ns-esc-char ::= “\” ( ... | ns-esc-slash | ... )
```

And that's then used in section 7.3.1. Double-Quoted Style, when defining valid double-quted scalars. From this it follows that the character sequence `"\/"` is a valid YAML representation of the single-character string `/`.

The page you linked to is unfortunately out of date, by a bit over a decade. YAML is indeed a superset of JSON, which is in fact the reason for adding this specific rule back in 2009.

**Comment by perlpunk** [comment]
Regarding that JSON::XS page on metacpan - the author could do us a great favor and explicitly mention the things in YAML 1.2 that he thinks are still incompatible with JSON, instead of just saying "have been documented".
I believe what he wrote could come from the fact that he tried out YAML **implementations** that were written for an earlier version of the spec, but not actually looking at the spec.

**Comment by eemeli** [comment]
Closing this, as there's no actual bug here to fix.
