### ISSUE TITLE
minFractionDigits ignored when converting to JSON

### ISSUE THREAD

**Issue by cemerick** [eemeli/yaml#315]
**Describe the bug**
#97 describes the addition of `minFractionDigits` as the way the library will retain precision on floats when re-emitted. This works when stringifying to yaml, but not to JSON.

**To Reproduce**
```
> yaml.parseDocument("a: 5.0").contents.toJSON()
{ a: 5 }
```

**Expected behaviour**

The above snipped should yield the string `{ a: 5.0 }`, to match the precision of the float in the source yaml.

**Versions (please complete the following information):**

- Environment: node v10.20.1
- `yaml`: yaml@2.0.0-8

**Comment by eemeli** [comment]
Perhaps the [docs on this](https://eemeli.org/yaml/#document-methods) aren't sufficiently clear? A [`toJSON()` method](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify#tojson_behavior) isn't meant to return a string, but a representation of the object in question in a form that's JSON-compatible.

So for example in the snippet that you posted, `{ a: 5 }` is not a string, it's an object with a key `a` and a value `5`.

But you're right that the library doesn't currently provide for a good JSON emission API. And that does sound like an interesting problem to fix, esp. considering JSON with comments.

**Comment by cemerick** [comment]
I did read the "description" of the `toJSON()` method, but the `any` return type didn't register with me that it wasn't actually emitting JSON. (I had been passing the result through a function that happened to `JSON.stringify` anything that wasn't already a string, so the mismatch of expectations and reality wasn't immediately obvious.) Sorry for that.

Indeed, JSON emission would be very useful. I suspect I'll be able to whip something up that suits the subset of yaml we're using/accepting until then.

**Comment by cemerick** [comment]
A final followup to anyone that comes across this: I needed a JSON emission routine, and this ended up fitting the bill (at least so far, and for the [not small FWIW] set of test cases the current project tracks):

```js
function emit(out, v) {
  const emitScalar = function (v) {
    let s = JSON.stringify(v.toJSON());
    out.write(s);
    if (v.minFractionDigits && s.indexOf(".") == -1) out.write(".0");
  }
  let emitItems = function (items, fn) {
    items.forEach((v, i) => {
      fn(v);
      if (i < items.length - 1) out.write(",");
    });
  }
  if (yaml.isMap(v)) {
    out.write("{");
    emitItems(v.items, i => {
      emit(out, i.key);
      out.write(":");
      emit(out, i.value);
    })
    out.write("}");
  } else if (yaml.isSeq(v)) {
    out.write("[");
    emitItems(v.items, i => emit(out, i));
    out.write("]");
  } else if (yaml.isScalar(v)) {
    emitScalar(v);
  } else {
    // TODO need some reporting to stderr
    process.exit(1);
  }
}
```

Absolutely ymmv for the above code, but I thought I'd leave it here just in case someone needed something similar until an "official" approach does it properly. :smile:
