### ISSUE TITLE
`:@` reported as an invalid plain value in some flow contexts

### ISSUE THREAD

**Issue by cemerick** [eemeli/yaml#316]
**Describe the bug**
The character sequence `:@` is a valid flow plain value, but is reported as invalid in some contexts.

Other sequences involving characters that are barred from _starting_ a plain scalar are also reported as invalid, including `` ` ``, `%`, and probably others.

**To Reproduce**

```js
yaml.parseDocument("[[], :@]")
```

The reported error is `Plain value cannot start with reserved character @ at line 1, column 7:\n\n[[], :@]\n      ^\n`

**Expected behaviour**

A successful parse, with document contents of a sequence with two members (one empty sequence, and the string scalar ":@").

**Versions (please complete the following information):**

- Environment: node v10.20.1
- `yaml`: yaml@2.0.0-8

**Additional context**
I found mixed performance on this example (libfyaml and libyaml both parse successfully, but pyyaml and others do not), so I asked in the main YAML matrix chat. [ingy confirmed](https://matrix.to/#/!rqjZtudXEGTclzhLdC:yaml.io/$ibmEaOVHvNcvuMv6tqGeKs4LkWilJiGzMM1JomJdj7k?via=yaml.io&via=matrix.org) that the input text is valid yaml, and suggested filing an issue on the yaml test suite, which I will be doing shortly.

**Comment by cemerick** [comment]
ingy further suggested that this might be a regression, and so it is: with yaml@1.10.2, the repro in the report here works as expected.

**Comment by ingydotnet** [comment]
See https://spec.yaml.io/main/playground/javascript?input=W1tdLCA6QF0=

**Comment by ingydotnet** [comment]
Discussion happened in https://matrix.to/#/#chat:yaml.io so read that too...

**Comment by eemeli** [comment]
Thank you for spotting this! This was a lexer bug: a flag for tracking if a flow-collection key is a json-node was not being reset after the `,` character. The first `[]` set this flag, and then when parsing `:@` it was still mistakenly on, leading to the `:` to be considered as a separator that does not need a subsequent space, and hence ending up with a mis-parsed value of `@`, i.e. a reserved character. And that's then the error that you actually saw.

**Comment by cemerick** [comment]
I'm glad the report was helpful.

FWIW, I've upgraded my installation to master, and I can confirm the fix is effective. I really appreciate the super-fast turnaround, thank you for the great library. :smiley:
