### ISSUE TITLE
[Feature request] Stringify: Wrapping comments at specified width

### ISSUE THREAD

**Issue by leipert** [eemeli/yaml#322]
Thanks for this wonderful library!

Would you be interested in a contribution that wraps comments at the specified with during `stringify`?

e.g.

```yaml
foo:
  - This is an item
  # This is a very long comment in order to demonstrate wrapping at 80 characters. Isn't that beautiful?
  - That is an item
```

would result in 

```yaml
foo:
  - This is an item
  # This is a very long comment in order to demonstrate wrapping at 80
  # characters. Isn't that beautiful?
  - That is an item
```

**Comment by eemeli** [comment]
@leipert Are you still interested in working on this, or does the `commentString` option solve the issue for you sufficiently well?

**Comment by eemeli** [comment]
Closing as presumably resolved.
