### ISSUE TITLE
Incorrect error for flow sequence with flow mapping 

### ISSUE THREAD

**Issue by evidolob** [eemeli/yaml#328]
**Describe the bug**
When parser parse:
```yaml
foo: [ {
  bar: 1
} ]
```

it generate:
```
Expected flow map to end with }
Expected flow sequence to end with ]
Unexpected flow-map-end token in YAML stream: "}"
Unexpected flow-seq-end token in YAML stream: "]"
```

For  `]` in third line

**To Reproduce**
Parse sample and see errors

**Expected behaviour**
No errors as sample is valid YAML

**Versions (please complete the following information):**

- Environment: Node.js v14.16.0
- `yaml`: 2.0.0-8

**Additional context**
Reported in https://github.com/redhat-developer/vscode-yaml/issues/631

**Comment by eemeli** [comment]
This is in fact technically invalid YAML, as is this:

```yaml
foo: [
  bar
]
```

This is determined by the spec in [section 8.2.3](https://yaml.org/spec/1.2.2/#823-block-nodes):
> Flow nodes must be indented by at least one more space than the parent block collection.

However, this library includes a relaxation that allows for the closing brace of a flow collection embedded in a block collection to have the same indentation level as its parent, so the above is parsed without compaint. This relaxation is not extended for inner flow collections, however.

I'm now thinking that something ought to be done about the current situation, but I'm not entirely sure what. I think at least the following non-exclusive options are available:
1. Improve the error message, or at least fix the character it's pointing to.
2. Extend the current relaxation to allow for nested flow collections to also use the parent's indent level.
3. Add a warning about this being technically invalid.
4. Remove this relaxation, and follow the spec more strictly.
5. Do nothing.

Thoughts/opinions on next steps here? As some of the above actions might be a (very limited) breaking change, I'm going to consider the resolution of this a blocker on the final `yaml@2` release.

I'm also thinking that e.g. lint/validator users of `yaml` might benefit from a compatibility schema, which could accept but warn about values and expresssions that are not accepted by all YAML libraries. But I'll file a separate issue about that.

**Comment by evidolob** [comment]
I think 1 and 3 as stating point should be enough, for users to understand that they `yaml` not valid.

**Comment by eemeli** [comment]
#335 adds a warning for the not-well indented closing brace, provided that the new `compat` option has a non-empty value. I don't think a warning for that makes sense for the default case, as that'd just be excessively verbose.

Separately, the error is improved. This is what's now generated, note in particular the code for the first two errors:

```yaml
foo: [ {
  bar: 1
} ]
```

```
[BAD_INDENT] Flow map in block collection must be sufficiently indented and end with a }
[BAD_INDENT] Flow sequence in block collection must be sufficiently indented and end with a ]
[UNEXPECTED_TOKEN] Unexpected flow-map-end token in YAML stream: "}"
[UNEXPECTED_TOKEN] Unexpected flow-seq-end token in YAML stream: "]"
```

For input where the flow collection is a top-level node, the error is a bit different:

```yaml
{ bar: 1
```

```
[MISSING_CHAR] Flow map must end with a }
```

There were also two off-by-one bugs in tracking the offset that are now also fixed.

@evidolob Would these changes work for your use case?

**Comment by evidolob** [comment]
@eemeli Yes, that should work, thx!
