### ISSUE TITLE
Tag Function for Antiquotation

### ISSUE THREAD

**Issue by markandrus** [eemeli/yaml#331]
I have a tool which produces YAML documents. The tool produces YAML documents which include user-supplied inputs. I cannot handle all the edge cases of escaping these inputs, ensuring proper formatting, etc., which is why I use this library. (By the way, it's a great library!)

In order to use this library more easily, I created a [tag function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) which supports antiquotation. Now I can more easily write out YAML documents, specifying exactly where I want user-supplied inputs to be injected. For example,

```ts
import { yaml, pair } from 'yaml'  // Just an idea…

const xs = ['*']

const doc: Document.Parsed<ParsedNode> = yaml`\
foo: bar
baz:
  qux: ${doc => doc.createNode(xs)}
`

// foo: bar
// baz:
//   qux:
//     - "*"
```

Antiquotation works by generating a unique string-valued token for every value to be introduced into the YAML document. We then parse the YAML document and `visit` it, replacing all occurrences of the tokens with their corresponding values. I also found it useful to be able to

* **optionally extend sequences** — if the value constructor returns `undefined`, omit the entry from the list.
* **optionally extend maps** if the value constructor returns `undefined`, omit the key from the map. I could only implement this with a special function for introducing pairs (not sure if it's the right term). Maybe this could be better.

    ```ts
    const doc: Document.Parsed<ParsedNode> = yaml`\
    foo:
      ${pair('included', doc => doc.createNode(['*']))}
      ${pair('excluded', _ => undefined)}
    `

    // foo:
    //   included:
    //     - "*"
    ```

I did not solve the problem of extending sequences with more than one element. And maybe instead of letting `undefined` mean "remove me" this should reuse `visit.REMOVE`.

The implementation follows.

<details>
<summary>Implementation</summary>

```ts
import { randomUUID } from 'crypto'

import { Document, isScalar, Node, Pair, ParsedNode, parseDocument, visit } from 'yaml'

export type Value = symbol|number|Node|Pair

/**
 * A function for constructing values to include within a YAML document. Return null or undefined to remove the value.
 */
export type ValueConstructor = (doc: Document.Parsed<ParsedNode>) => Value|undefined|null

/**
 * The type for introducing keys to maps within a YAML document.
 */
export interface PairConstructor {
  type: 'PAIR'
  key: string
  value: ValueConstructor|string
}

/**
 * A function for introducing keys to maps within a YAML document. Return null or undefined to remove the key.
 * @param key the key to introduce to the map
 * @param value a function for computing the value
 * @returns a key/value pair for inclusion in a map
 */
export function pair (key: string, value: ValueConstructor|string): PairConstructor {
  return {
    type: 'PAIR',
    key,
    value
  }
}

/**
 * A tag function for constructing YAML documents which supports antiquotation.
 * @param strings the tagged template literal strings
 * @param ctors arguments provided to the tagged template literal for antiquotation
 * @returns a parsed YAML document
 */
export default function yaml (strings: TemplateStringsArray, ...ctors: Array<ValueConstructor|PairConstructor|string>): Document.Parsed<ParsedNode> {
  const tokens: string[] = []

  let unparsed = ''
  for (let i = 0; i < strings.length; i++) {
    unparsed += strings[i]
    const ctor = ctors[i]
    if (ctor !== undefined) {
      const token = randomUUID()
      tokens[i] = token
      if (typeof ctor === 'object' && 'type' in ctor && ctor.type === 'PAIR') {
        unparsed += `${token}: {}`
      } else {
        unparsed += token
      }
    }
  }

  const doc = parseDocument(unparsed)

  visit(doc, {
    Map (_, node) {
      let didChange = false
      for (let i = node.items.length - 1; i >= 0; i--) {
        const item = node.items[i]
        if (!isScalar(item.key)) {
          continue
        }
        const key = (item.key).value
        if (typeof key !== 'string') {
          continue
        }
        const j = tokens.indexOf(key)
        if (j === -1) {
          continue
        }
        didChange = true
        const ctor = ctors[j]
        if (ctor === undefined) {
          node.items.splice(i, 1)
          continue
        } else if (typeof ctor === 'string' || !('type' in ctor) || ctor.type !== 'PAIR') {
          throw new Error('Programming error (this should never happen)')
        }
        const value = typeof ctor.value === 'string'
          ? doc.createNode(ctor.value)
          : ctor.value(doc)
        if (value === undefined || value === null) {
          node.items.splice(i, 1)
          continue
        }
        node.items[i].key = ctor.key
        node.items[i].value = value
      }
      return didChange
        ? node
        : undefined
    },
    Seq (_, node) {
      let didChange = false
      for (let i = node.items.length - 1; i >= 0; i--) {
        const item = node.items[i]
        if (typeof item !== 'string') {
          continue
        }
        const j = tokens.indexOf(item)
        if (j === -1) {
          continue
        }
        didChange = true
        const ctor = ctors[j]
        if (ctor === undefined) {
          node.items.splice(i, 1)
          continue
        } else if (typeof ctor === 'string') {
          node.items[i] = doc.createNode(ctor)
          continue
        } else if ('type' in ctor) {
          throw new Error('Programming error (this should never happen)')
        }
        const value = ctor(doc)
        if (value === undefined || value === null) {
          node.items.splice(i, 1)
          continue
        }
        node.items[i] = value
      }
      return didChange
        ? node
        : undefined
    },
    Scalar (_, node) {
      if (typeof node.value !== 'string') {
        return undefined
      }
      const i = tokens.indexOf(node.value)
      if (i === -1) {
        return undefined
      }
      const ctor = ctors[i]
      if (ctor === undefined) {
        return visit.REMOVE
      } else if (typeof ctor === 'string') {
        return doc.createNode(ctor)
      } else if ('type' in ctor) {
        return undefined
      }
      return ctor(doc) ?? visit.REMOVE
    }
  })

  return doc
}
```
</details>

Does it make sense to add such a function to this library? This is something I was thinking of in the context of #327, but my use case is different: I don't need to load YAML templates from disk; I can instead write them as tagged template literals.

**Comment by eemeli** [comment]
Why not use `new Document()` instead? Using your first example:

```js
import { Document } from 'yaml'

const xs = ['*']
const doc = new Document({ foo: 'bar', baz: { qux: xs } })
doc.toString()
```

```yaml
foo: bar
baz:
  qux:
    - "*"
```

To be clear, I'm not opposed to a tagged template literal API, but I don't think I'm seeing yet what benefit it gives.

**Comment by markandrus** [comment]
There are some cases where I want to control the formatting. I think the `new Document` wouldn't be as flexible in this regard? But it's a good suggestion! I might be able to use it more than I currently am.

**Comment by JacBian** [comment]
Perhaps it makes more sense to define a Template String, because yamL doesn't support such a definition. By customizing placeholders, the file itself is no longer standard YAML and has lost its universal meaning.

**Comment by JacBian** [comment]
`
var yamlStr = `
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: ${deployment.name}
          name: ${deployment.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${deployment.name}
          template:
            metadata:
              labels:
                app: ${deployment.name}
            spec:
              containers:
                - image:${deployment.image}
                  name:  ${deployment.name}
                  ports:
                    - containerPort: ${deployment.Port}
        `
`

**Comment by JacBian** [comment]
```
var yamlStr = `
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          labels:
            app: ${deployment.name}
          name: ${deployment.name}
        spec:
          replicas: 1
          selector:
            matchLabels:
              app: ${deployment.name}
          template:
            metadata:
              labels:
                app: ${deployment.name}
            spec:
              containers:
                - image:${deployment.image}
                  name:  ${deployment.name}
                  ports:
                    - containerPort: ${deployment.Port}
        `
```

**Comment by eemeli** [comment]
Okay, I'm starting to see the utility here. The first thing that needs to be hammered out is the API, i.e. what sort of things are accepted in expressions and how exactly they're handled. Also, does the place in the document where an expression is placed affect it in any way?

@markandrus I presume you have some initial thoughts on this?

**Comment by eemeli** [comment]
@markandrus Are you still thinking that this might be useful?

**Comment by markandrus** [comment]
I am using some functions at work for this, but never got them to place I was really happy with. The template string functions became awkward when I needed to support maps and lists.

**Comment by eemeli** [comment]
Closing this, as it doesn't look like anything is happening in this direction. Happy to reopen if there's active interest.
