### ISSUE TITLE
singleQuote is not applied consistently

### ISSUE THREAD

**Issue by octogonz** [eemeli/yaml#333]
**Describe the bug**

Version 2.0 of the library introduces a `singleQuote` option:

```ts
    /**
     * Prefer 'single quote' rather than "double quote" where applicable.
     *
     * Default: `false`
     */
    singleQuote?: boolean;
```

The option is not honored in some contexts.

**To Reproduce**
Steps to reproduce the behaviour.

Try this code sample:

```ts
const document = {
  a: '123',
  b: 'this: that'
}
console.log(yaml.stringify(document, {singleQuote: true}));
```

**Expected:** The correct output should be:
```
a: '123'
b: 'this: that'
```

**Actual:** The actual output is:
```
a: "123"
b: 'this: that'
```

**Versions (please complete the following information):**

- Environment: Node v14.15.4
- `yaml`: 2.0.0-8

**Comment by octogonz** [comment]
Looks like this was fixed recently in 78fbf36c0b0a3b3fbe5a7c265e286500655b7be0

@eemeli Could you publish a prerelease with this fix?  😇

**Comment by octogonz** [comment]
My scenario:  I found that if we render our Jest snapshots as YAML (instead of Jest's proprietary object notation), it improves readability and reduces the number of lines by roughly 36%.

However Jest wraps the YAML string inside backticks and also double-quotes.  Thus, single quoted YAML is needed to avoid lots of backslash escapes in the output.

**Comment by eemeli** [comment]
Done: https://github.com/eemeli/yaml/releases/tag/v2.0.0-9

**Comment by octogonz** [comment]
@eemeli `yaml@2.0.0-9` works awesome!  Thank you!
