### ISSUE TITLE
Including yaml inside yaml

### ISSUE THREAD

**Issue by Alex-Braine** [eemeli/yaml#341]
Hi
It would be great to have !include/import for including yaml inside yaml
Something like https://github.com/rafamel/yaml-import

**Comment by eemeli** [comment]
Something like this is being considered for inclusion in YAML 1.3, though possibly via a new `%IMPORT` directive. That might take still a while to really progress. In the meantime, it's entirely possible for e.g. the library you linked to provide a custom tag for use with `yaml`.
