### ISSUE TITLE
1.10.2 breaks yaml strings on whitespace  and does not allow to turn of the feature

### ISSUE THREAD

**Issue by jamo** [eemeli/yaml#356]
**Describe the bug**
It cuts the strings to multiple lines

**Expected behaviour**
values are allowed to be full width on a single line

**Versions (please complete the following information):**

- node 16
- `yaml`: 1.10.2 (latest from npm)

**Additional context**

**Comment by eemeli** [comment]
Have you tried setting the `YAML.scalarOptions.str.fold.lineWidth` option? https://eemeli.org/yaml/v1/#scalar-options
