### ISSUE TITLE
Whitespace is not preserved correctly when round-tripping JSON arrays

### ISSUE THREAD

**Issue by GeorchW** [eemeli/yaml#369]
I have another minor issue - the white space is not preserved correctly when round-tripping JSON arrays whose items exceed a certain length. Setting `lineWidth: 0` doesn't help either.

```
parseDocument('["the quick brown fox jumps over the lazy dog. lorem ipsum dolor sit amet"]').stringify({ lineWidth: 0 })
// expected: '["the quick brown fox jumps over the lazy dog. lorem ipsum dolor sit amet"]'
// actual:   '[\n  "the quick brown fox jumps over the lazy dog. lorem ipsum dolor sit amet"\n]'
```

**Versions:**

- Environment: Node.js v16.13.1
- `yaml`: 2.0.0-10

**Additional notes**

This is a very minor issue, it's not very critical to me; just wanted to make you know.

**Comment by eemeli** [comment]
Yeah, not going to fix this one. The document level does not retain all information about the input string's whitespace. If you need this level of control, you're probably better off working with the CST.

**Comment by GeorchW** [comment]
Okay, thanks!
