### ISSUE TITLE
Problematic naming of the folder `doc` under the build folder `yaml/dist/`

### ISSUE THREAD

**Issue by alirezamdz** [eemeli/yaml#384]
**Choosing a general string `doc` for the folder name which contains source code modules**.   

**Background:**
As a good practice, people will prune the `node_modules` during the build time as post-install on production builds. 
as an example `yarn autoclean` or the project `node-prune`  [here](https://github.com/tj/node-prune)
These prune functions use some pre-defined list of file and directory names, that are not necessary for an app, running on production. Like readme files, linters, documentations, and ... these files and directories will be removed from `node_modules` by the pruning job. 

**The issue:**
The `doc` directory is a candidate to be removed, you could see the predefined [list](https://github.com/tj/node-prune/blob/1159d4cac8090ca0b4a3d900ae81efb72558ea8a/internal/prune/prune.go#L96)
Seems after `yaml` migration to TS and the new build, the folder `doc` appears in the new build in `dist`!

**To Reproduce**

- install `node-prune` gloubaly or any other method that you prefer. (`npm i -g node-prune`)
- run `npm i yaml` in a project.
- run `node-prune`
if you navigate to the `/app/node_modules/yaml/dist/` you will see that the doc folder is removed by `node-prune`

**Expected behaviour**
Rename the `doc` folder to be safe. reserve the name `doc` or `docs` only for documentation not for the module source code.

**Versions:**
this bug occurs on the version `2.0.0` in which the directory [`doc`](https://github.com/eemeli/yaml/tree/master/src/doc) is introduced in the new TS build.

- Environment: Node.js tested in (16.14.0) but other versions will have the same issue
- `yaml`: 2.0.0
-  `node-prune` : 1.0.2

**Comment by eemeli** [comment]
I'm sorry, but no, this doesn't seem like a change I'm willing to accede to. Making it easier for random third-party tools to automagically remove things from packages seems like a non-goal for me.

It also looks like most of the projects in this scope are out of date or abandoned; yarn appears to have dropped `autoclean` in its v2 release, and the `node-clean` that's on npm isn't the one you linked to, but [this bash script](https://github.com/tuananh/node-prune) with 10 commits from 2017 in its history.

If you would like to prune files from a `yaml` installation, you should be able to remove either the `browser/` or `dist/` directories in their entirety, depending on your runtime environment.

**Comment by alirezamdz** [comment]
Hey Eemeli. Thanks for your feedback. first thanks for the very nice `yaml` package.
why it's a big deal to rename a folder? you could name it for example `documentApi` or `document-api`!

And about the bash script, they copied the reference mostly from the `yarn` here is the [yarn filter](https://github.com/yarnpkg/yarn/blob/master/src/cli/commands/autoclean.js#L25) so this it's a very small script, although it is old and has no new commits, it does what it does. 

And yes you are right about the approach to properly prune files, but It's more work to build a customized prune script versus using a small old package that prunes the common files and folders. In the end, you just need to reduce your Docker image size.
Imagin a CI pipeline that creates 100 docker images every day on each source code commit... what's the problem to save some MB on every image! so these third-party prune tools are useful sometimes ;)

**Comment by alirezamdz** [comment]
with all respect. your lib your wish :) sorry for wasting your time.
for now, we downgrade to `yaml@1.10.2` and find a solution later. I will close the issue.
Thank you.

> And that's why I mentioned above that if you care about pruning the yaml npm package, you should be able to drop either browser/ or dist/ and save 60-80 kB (compressed). But to do so, you'll need to configure whatever tool you're using appropriately, or find some better one that can e.g. parse the package.json "exports" data and determine things from there.

there are 1500+ packages in our `node_modules`! Our intention is not to prune the `yaml` package individually. we prune the whole `node_modules` and the `yaml` package is one of them in there. we could not provide custom pruning one by one for all of them. Actually, we could, but who has time for that? As I mentioned executing one script which just removes general doc, docs, examples, tests, readme,.. is zero effort.
every time we run this general prune script we clean up 200+MB with zero configurations. that's the idea.

**Comment by eemeli** [comment]
Just out of interest, if size is a concern for you, why aren't you using a bundler like Rollup to minimize your deployed app size? That would allow you to leave out the `node_modules` entirely from your Docker image.

**Comment by eemeli** [comment]
@linxux Are you getting this error after using some tool that's removed the `node_modules/yaml/dist/doc/` folder? If so, this is a bug in that tool.

**Comment by linxux** [comment]
@eemeli 
Right. I will try on a minimum project to check this and get back to you later.

**Comment by vachigaggl** [comment]
I just lost a whole afternoon on this! I know that github issues are not the right forum to vent one's anger at package maintainers that put their principles above other peoples' problems, but my anger levels are quite high right now. 

I do not use this lib on purpose, it is a dependency of another lib. Neither was I using any form of node-prune or autoclean on purpose. I will stop doing so.
I was not aware that my project had a .yarnclean file which causes yarn 1.0 to run yarn autoclean with every yarn install. I got this error when running webpack:
`Error: Cannot find module '../doc/directives.js'`

Solution:
Add this line to` .yarnclean` file:
`!**/yaml/dist/**/doc`

I consider this a workaround because this package does not follow common best practices. 
Please reconsider changing the directory name.

**Comment by jordanstephens** [comment]
Thanks for your work on this package. I wanted to note that I also lost a fair amount of time today tracking this down. I don't think it's a bug or any kind of problem with yarn, it seems like it's just a common configuration that silently removes part of your package's source code. 🤷 

I didn't know there was a `.yarnclean` file. I also don't know how the entries in that file are typically populated. However, if this configuration is indeed common, then I think it would be worth it to rename the directory. I'd be happy to open a PR to do it. Let me know if you're interested.

I understand there is a slippery slope component to this argument in theory, but practically, it seems like renaming this directory would save a few lost afternoons in the future. 💛

**Comment by eemeli** [comment]
> However, if this configuration is indeed common, then I think it would be worth it to rename the directory.

This configuration is not common. It was a yarn v1 feature that requires for a `.yarnclean` file to be manually created. It's been in maintenance mode now for two years, and will probably end-of-life sometime soon.

As I discuss above in this thread, it was a bad idea, and I'm not really interested in making it easier for such a tool to exist.

On the other hand, if a relevant authority like Node.js or npm were to come up with recommendations on directory names and structures in published packages (none currently exist), I would be happy to follow such.
