### ISSUE TITLE
{blockQuote: 'literal'} option applies a '>' or '>-' instead of '|' or '|-' if one of the lines is >=79 characters

### ISSUE THREAD

**Issue by ghuser** [eemeli/yaml#388]
**Describe the bug**
I use `bloqQuote: 'literal'` option when stringifying from an object to get `|` character and no additional newlines. This works, but if a line with `>=79` characters exists it uses `>`. The same happens if the string ends with a newline. Instead of using `|-` it uses `>-`.

**To Reproduce**

```js
const YAML = require('yaml');

let x78NewlineAtTheEnd = String.raw`{"description": "firstline\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\nlastLine\n"}`
let x79NewlineAtTheEnd = String.raw`{"description": "firstline\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\nlastLine\n"}`
let x78 = String.raw`{"description": "firstline\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\nlastLine"}`
let x79 = String.raw`{"description": "firstline\naaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa\nlastLine"}`

console.log(YAML.stringify(JSON.parse(x78NewlineAtTheEnd), {blockQuote: 'literal'}));
console.log(YAML.stringify(JSON.parse(x79NewlineAtTheEnd), {blockQuote: 'literal'}));
console.log(YAML.stringify(JSON.parse(x78), {blockQuote: 'literal'}));
console.log(YAML.stringify(JSON.parse(x79), {blockQuote: 'literal'}))
```

Results:

```
description: |
  firstline
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  lastLine

description: >
  firstline

  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  lastLine

description: |-
  firstline
  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
  lastLine

description: >-
  firstline

  aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa

  lastLine

```

**Expected behaviour**

The results above should all use `|` and `|-` character and not `>` and `>-`.

**Versions (please complete the following information):**

- Environment: `v16.14.2`
- `yaml`: `1.10.2`

**Additional context**

- I tried using `lineWidth: 0`, or `lineWidth: 200` to see whether it is related to that, but the problem persists.
- `indent` value affects the line width on which the problem occurs. E.g. if I use `indent: 1` (instead of 2) it needs to add one more character to the line for the problem to occur.

**Comment by eemeli** [comment]
This is fixed in `yaml@2`. Is there anything blocking you from updating to that?
