### ISSUE TITLE
directives > ToStringOptions not working as expected

### ISSUE THREAD

**Issue by skoblenick** [eemeli/yaml#389]
**Describe the bug**

**To Reproduce**

1. setup the project

    ```
    mkdir yaml-issue && cd $_
    npm init -y
    npm i -D yaml@2.0.1
    touch index.ts
    ```

1.  Add the following code to `index.ts`:

    ```
    import fs from 'fs';
    import path from 'path';
    import { parse, stringify } from 'yaml';
    
    const jsonConfig = {
       name: {
          firstName: 'Johnny',
          lastName: 'Appleseed'
       } 
    };
    
    const yamlConfig = stringify(jsonConfig, null, {
        directives: true,
      });
    
    fs.writeFileSync(path.resolve(__dirname, './config.yml'), yamlConfig);
    ```

1.  Run the script from terminal:

    ```
    $ npx ts-node $PWD/index.ts
    
        return new TSError(diagnosticText, diagnosticCodes);
               ^
    TSError: ⨯ Unable to compile TypeScript:
    index.ts:13:3 - error TS2322: Type 'true' is not assignable to type '(Directives & (boolean | null)) | undefined'.
    
    13   directives: true,
    ```

**Expected behaviour**

Expect to be able to set the value to the value of `true` as documented here https://eemeli.org/yaml/#tostring-options
so that the addition is done at `---` the top of the yaml file.

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- `yaml`: 2.0.1
- `node`: 14.18.2
- `ts-node`: 10.0.0

**Comment by eemeli** [comment]
Thank you for reporting this! There was an internal document option used only by the composer with the same `directives` name. That's now been renamed as `_directives` so that the TS types don't conflict.
