### ISSUE TITLE
Support YAML.load('pathToYmlFile.yml')

### ISSUE THREAD

**Issue by kienpham2000** [eemeli/yaml#39]
awesome package, I'm using it on one of my project and was wondering if you are willing to support something like YAML.load() where you can read in the file from fs and parse at the same time? 

If you are not against this approach, I can help send in PR. 

Thanks.

**Comment by kachkaev** [comment]
That looks like something outside of the package scope and makes it harder to use it in the browser environment. Loading data from fs (remote server, s3, whatever) _and_ parsing it as yaml is provably a topic for a wrapper package rather than a feature of the core one.

**Comment by kienpham2000** [comment]
cool make sense.
