### ISSUE TITLE
string "yes" is always converted to boolean

### ISSUE THREAD

**Issue by skoblenick** [eemeli/yaml#391]
**Describe the bug**
I have a document  who's schema expects the value of `"yes"` to be a string not a boolean. The `stringify` method is forcing the "yes" string to a boolean. I have tried to use a custom replacer but the value always comes out as `yes` rather than `"yes"`. In this case expectation is the string `"yes"`, a literal string not a boolean value by the application reading the yaml config, thus shouldn't be confused with true.

Is there an option i am missing that would support this?

**To Reproduce**

1. Setup project:
    ```
    mkdir issue && cd $_
    npm init -y
    npm i -D ts-node yaml@2.1.0
    ```

1.  Update `package.json` adding a script for ts-node:

   ```json
   {
      //...
      "scripts": {
              "ts-node": "ts-node"
      }
      //...
  }
   ```

1. Create a yaml template named: `my-config.yml.tmpl`:
    ```yaml
    ---
    parent:
       childA: "yes"
       childB: "foo"
       childC: true
       childD: |-
           i am multiline
           i shouldn't be crushed
     ```
1. Create the following script `index.ts` with the contents:

    ```ts
    import { parse, stringify } from "yaml";

    import fs from "fs";
    import path from "path";

    const templateYaml = fs.readFileSync(
       path.resolve(__dirname, "./my-config.yml.tmpl"),
       "utf-8"
    );

    const data = parse(templateYaml);

    data.parent.childC = false;

    const yml = stringify(
       data,
       (key, value) => {
          if (key === "childA") {
             return "yes"; // also tried return `"yes"`; which returns '"yes"' in the yaml file output
          }
          return value;
       },
       {
           directives: true,
        }
     );
     fs.writeFileSync(path.resolve(__dirname, "./my-config.yml"), yml);
     ```
 
1.  Execute the script with:

    ```shell
    npm run ts-node $PWD/index.ts
    ```

**Expected behaviour**
Expect `"yes"` to remain a string and not be converted to a boolean `yes`

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- `yaml`: 2.1.0
- Node: 14.8.2

**Comment by skoblenick** [comment]
found I had to add `version: "1.1"` to the stringify options for the effect I desire with the following replacer:

```
(key, value) => {
    if (typeof value === "string") {
      return `${value}`;
    }
    return value;
  },
```

but only wraps the value of "yes" in double quotes, all other strings are left unquoted. Not sure if this is a different bug, but wrapping the value in backtick and double-quotes results in: `'"my string"'`

**Comment by eemeli** [comment]
The scalar value `yes` is parsed as a boolean `true` in YAML 1.1, but not in the YAML 1.2 that this library defaults to. If the other YAML processors you're dealing with expect YAML 1.1 content, you should indeed use the `version: '1.1'` option.

To control how scalar values are output, there are a few things you can do:
1. Use `parseDocument()` and work within the Document structure. Calling `parse()` discards the node style information and emits just the YAML contents.
2. Set the `defaultStringType` option.
3. Ensure that you're using an appropriate `version` option to produce YAML that's compatible with its other consumers' expectations.
