### ISSUE TITLE
Stringify formatting conflicts with yamllint

### ISSUE THREAD

**Issue by lucasgonze** [eemeli/yaml#398]
**Describe the bug**

It is common for developers to ingest YAML using this library, modify it, output it, and then ultimately send the output through yamllint for checking. This will fail because the stringify() output is formatted in ways incompatible with yamllint, which will throw errors.

1. "too few spaces before comment": yamllint wants two spaces before a comment at the end of a line, like `  # this`
2. \n sequences in yaml literals will be output as multiline strings, which simply are not equivalent
3. literals in brackets will be padded with spaces, `[ a ]` instead of `[a]`

**To Reproduce**

1. clone git@github.com:magma/magma.git
2. cd magma/.github/workflows
3. use this yaml library to ingest, stringify, and save 
4. run yamllint on the saved files

**Expected behaviour**

yaml and yamllint should be in sync. By default there shouldn't be collisions.

**Additional context**

This came up via pin-github-actions: https://github.com/mheap/pin-github-action/issues/74

**Comment by eemeli** [comment]
Aligning the default `yaml` output exactly with the default options of `yamllint` is not planned. There is no one truly right/official way of formatting YAML -- much like there is no one right way to format JSON -- and each implementation makes different choices.

However, `yamllint` is quite configurable, and I'd encourage you to look at e.g. [`comments.min-spaces-from-content`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.comments) and [`braces/brackets.min-spaces-inside`](https://yamllint.readthedocs.io/en/stable/rules.html#module-yamllint.rules.braces) for options that would match what's used in this project by default.

I'm not really sure what issue you're seeing with newlines in scalar values; could you give a specific example of that issue?

In general, I'd be happy to include somewhere an example `yamllint` config. If you do end up putting one together, would you be interested in sharing it?

**Comment by lucasgonze** [comment]
An example of the newline issue.

Input yml:
`SLACK_MESSAGE: "COMMIT TITLE:\n ${{steps.commit.outputs.title}}\n\n\n GIT STATUS OUTPUT:\n ${{env.GIT_STATUS}}"`

Output yml:
`          SLACK_MESSAGE: "COMMIT TITLE:

            \ ${{steps.commit.outputs.title}}



            \ GIT STATUS OUTPUT:

            \ ${{env.GIT_STATUS}}"`

**Comment by lucasgonze** [comment]
About the documentation project, I think this is the project:

1. Get a reasonably thorough batch of yaml test data
2. Read in, convert to yaml object, stringify, write out
3. Run through yamllint 
4. If no errors reported, send you the config file
5. Else tweak config file to eliminate errors, GOTO 3

I don't mind taking that on.

**Comment by ssbarnea** [comment]
To be honest, I am more inclined to aim matching prettier yaml formatting style instead of yamllint as its popularity is more than an order of magnitude bigger.

Even if we use yamllint as a dependency of ansible-lint we adopted a custom config that is matching prettier style. Prettier is also js based project, which means that you could use it directly if you want.

**Comment by lucasgonze** [comment]
I totally get why you'd target Prettier instead of yaml-lint, but it's out of scope for me personally, since I'd have to change a module that I don't own.
