### ISSUE TITLE
Distinguish SemanticError and SyntaxError

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#4]
From the perspective of a formatter, we don't care semantic errors like #3, we should format it anyway, so it'd be better to have a way to distinguish them.

**Comment by eemeli** [comment]
How would you differentiate semantic errors from syntax errors?

**Comment by ikatyang** [comment]
It seems duplicate key is the only semantic error, I'm not sure how to define it but it should be something valid on the AST level.

**Comment by ikatyang** [comment]
Some of the SemanticError listed above looks like SyntaxError to me, for example, `'Chaining flow sequence pairs is invalid (e.g. [ a : b : c ])'`, I'd expect it a flat structure instead of the nested one, but I know that's probably based on the implementation.

Can we have some unique id (e.g. `error.id === 1`, etc.) so that I could safely filter some of them without looking into the error message?

**Comment by eemeli** [comment]
The thing is, any one of the "semantic" errors makes the document as a whole invalid YAML, and up until yesterday there was no distinction being made; even now `YAMLSemanticError` still extends `SyntaxError` just as `YAMLSyntaxError` does. They're just not detected by the AST.

However, the distinction they you can now make is that if you've only got "semantic" errors you can be more certain that the AST is not horribly broken. The particular place where this makes the "semantic" particularly "syntax" is with collections, as the AST is as liberal as possible with them to make sure they're completely parsed even if really broken.

TBH I don't see the value in including an `id` with every error, as I'm not convinced that some subset of them should be considered as less errors than the others. If this is not the use case you're thinking of, maybe I've not understood right what you're intending to do as a result of the filtering?

**Comment by ikatyang** [comment]
Sorry, you're right. After second thought I realized that my suggestion didn't make sense. The originally YAMLSyntaxError should be enough and we should only ignore YAMLReferenceError and YAMLWarning from a formatter perspective.

Looking forward the new release! ❤️
