### ISSUE TITLE
FlowChar: node.setOrigRanges is not a function

### ISSUE THREAD

**Issue by ikatyang** [eemeli/yaml#40]
version: 1.0.0-rc.8

```js
const YAML = require('yaml').default

YAML.parseCST('{ : }\r\n').setOrigRanges()
```

Expected:

no error.

Actual: 

```
TypeError: node.setOrigRanges is not a function
    at items.forEach.node (yaml/dist/cst/FlowCollection.js:144:21)
```

https://github.com/eemeli/yaml/blob/21633235dfafe60796213e42b5ba1903413a2df5/src/cst/FlowCollection.js#L113-L119

https://github.com/eemeli/yaml/blob/21633235dfafe60796213e42b5ba1903413a2df5/src/cst/FlowCollection.js#L32

**Comment by eemeli** [comment]
Should also update the docs for this; esp. as they didn't get updated to include the easlier refactoring of FlowChar into an object.
