### ISSUE TITLE
Not able to parse line breaks without indentation in double-quoted strings

### ISSUE THREAD

**Issue by PhilippWendler** [eemeli/yaml#403]
**Describe the bug**

Consider the following YAML document:
```yaml
key1: "value
continued"
key2: "value\
continued"
```
Admittedly, I am not 100% sure whether this is valid YAML because I found the spec too difficult to understand, but I believe it is because both [yamllint](http://www.yamllint.com/) and [yq](https://github.com/kislyuk/yq) accept it.

Yaml 2.1.1 rejects both of the string values with the following error messages:
```
Missing closing "quote at line 1, column 13:

key1: "value
            ^

Implicit keys need to be on a single line at line 2, column 1:

key1: "value
continued"
^

Missing closing "quote at line 3, column 14:

key2: "value\
             ^

Implicit map keys need to be followed by map values at line 4, column 1:

key2: "value\
continued"
^^^^^^^^^^

```
Interestingly,Yaml 1.10.2 rejects only the first string, but accepts the second string:
```
Multi-line double-quoted string needs to be sufficiently indented at line 1, column 7:

key1: "value
      ^^^^^^…
```
So if this is valid YAML, it is partially a regression from 1.x to 2.x.

Note that if I add spaces before `continued`, both string values are successfully parsed.

If my document is indeed invalid YAML, at least the error message from the parser is confusing, because it mentions only that implicit keys need to be on a single line, but with the added indentation, multi-line values are accepted by the library.

**To Reproduce**

```js
const YAML = require('yaml')

const doc = "key1: \"value\ncontinued\"\nkey2: \"value\\\ncontinued\""
console.log("---")
console.log(doc)
console.log("---")

const yaml = YAML.parseDocument(doc, {strict: false, prettyErrors: true})
console.log(yaml.errors.map(e => e.message.toString()).join("\n"))
```

**Expected behaviour**
I expect the document to be parsed just like the following (this is what yamllint and yq do):
```yaml
key1: "value continued"
key2: "valuecontinued"
```

**Versions (please complete the following information):**

- Environment: Node v14.19.3
- `yaml`: 1.10.2 and 2.1.1

**Comment by eemeli** [comment]
> Consider the following YAML document:
> 
> ```yaml
> key1: "value
> continued"
> key2: "value\
> continued"
> ```
> 
> Admittedly, I am not 100% sure whether this is valid YAML because I found the spec too difficult to understand, but I believe it is because both [yamllint](http://www.yamllint.com/) and [yq](https://github.com/kislyuk/yq) accept it.

This is not valid YAML, as the lines starting with `continued` are not sufficiently indented to be considered a part of the mapping values. It is unfortunate that other tools accept this input without complaint, as it easily leads to incompatibilities between different implementations.

> Interestingly,Yaml 1.10.2 rejects only the first string, but accepts the second string:

This was a bug in `yaml@1`, and so is not a regression but a fix in `yaml@2`.

**Comment by PhilippWendler** [comment]
Ok, thanks a lot for looking into this!
