### ISSUE TITLE
Merge operator `<< : *foo` literally makes obj with key name `<<`

### ISSUE THREAD

**Issue by dylanh724** [eemeli/yaml#408]
**Describe the bug**
When attempting to use the merge operator (YAML 1.2.2) with npm pkg `yaml`, it 1/2 works: The children *are* copied, but wrapped around an unexpected object named "<<".

**To Reproduce**
```
foo1: &foo1
  bar1: true
  bar2: false
foo2: 
  <<: *foo1
```
Then parse it:
```
const { parse } = require('yaml');
const fs = require('fs');

const yaml = fs.readFileSync(getPathToYaml(), 'utf8');
const json = parse(yaml);
```

Linters show this is np, but when I parse it, I get:
```
{
  "foo1": {
    "bar1": true,
    "bar2": false
  },
  "foo2": {
    "<<": {
      "bar1": true,
      "bar2": false
    }
  }
}
```

**Expected behaviour**
Expected a parse result to look like:
```
{
  "foo1": {
    "bar1": true,
    "bar2": false
  },
  "foo2": {
    "bar1": true,
    "bar2": false
  }
}
```
without the nested `"<<"` obj.

**Versions (please complete the following information):**

- Environment: Node v16.14.0

- `yaml`: yaml doc 1.2.2, npm yaml 2.1.1

**Additional context**
Following the docs, it feels like this should parse correctly - either a bug, or doc typo.

**Comment by dylanh724** [comment]
## Update
This is definitely a bug. When I use an [online sandbox for yaml->json](https://onlineyamltools.com/convert-yaml-to-json), the expected output is what I thought it should be:

![image](https://user-images.githubusercontent.com/8840024/186831701-5462f6aa-f918-4f6b-ace3-02a09c0c2889.png)

If it helps, I also use `yarn v3.2.2` with "zero install" config. Are you guys all _yarn'd up_?

**Comment by Lemmingh** [comment]
<https://github.com/eemeli/yaml/blob/96c699375abf6980ea5158e6ed2e86cff2927636/docs/09_yaml_syntax.md?plain=1#L79>
<https://github.com/eemeli/yaml/blob/96c699375abf6980ea5158e6ed2e86cff2927636/docs/03_options.md?plain=1#L97>

**Comment by dylanh724** [comment]
Oh wow! Thank you so much - and my apologies. I am still new to yaml, so I must have followed a dated tutorial (gah)! At least this will be here for people to search issues and facepalm instead of spend time submitting a false-positive bug ;)

**Comment by Porges** [comment]
> @dylanh724  Oh wow! Thank you so much - and my apologies. I am still new to yaml, so I must have followed a dated tutorial (gah)! At least this will be here for people to search issues and facepalm instead of spend time submitting a false-positive bug ;)

Note that you can explicitly enable it for YAML 1.2 via passing the options `{merge: true}` to `parse`.
