### ISSUE TITLE
Package not valid error 

### ISSUE THREAD

**Issue by AjitKP** [eemeli/yaml#411]
**Describe the bug**
This package name is not valid, because name can only contain URL-friendly characters.
Not Found - GET http://nginx-redirector.repo-cache.svc.cluster.local/yaml/-/yaml-1.10.2.tgz

![image](https://user-images.githubusercontent.com/25340339/192429453-9d7d5959-6d12-418a-ac6f-af93895d2138.png)

**To Reproduce**
npm install yaml --save

**Comment by eemeli** [comment]
This isn't a bug with `yaml`, but with your custom registry settings.
