### ISSUE TITLE
Unable to import yaml package using require with yaml 2.1.3

### ISSUE THREAD

**Issue by siva-sundar** [eemeli/yaml#414]
**Describe the bug**
Unable to import yaml package using require.

<img width="965" alt="yaml-error" src="https://user-images.githubusercontent.com/15258941/194041269-f00aa40a-0ea0-49da-84bc-6cbe0c027254.png">

**To Reproduce**
Steps to reproduce the behaviour.
* Try require('yaml')

**Versions (please complete the following information):**

- Environment: Node.js  v12.22.9
- `yaml`: 2.1.3

**Comment by eemeli** [comment]
Duplicate of #394.
