### ISSUE TITLE
Incorrect .js imports when used with deno

### ISSUE THREAD

**Issue by ctwrs** [eemeli/yaml#426]
**Describe the bug**
When trying to use this lib in deno I get:

    error: Uncaught (in promise) TypeError: Module not found "https://deno.land/x/yaml@v2.1.3/src/parse/parser.js".
    at https://deno.land/x/yaml@v2.1.3/src/public-api.ts:16:24

**To Reproduce**
1. Install Fresh or any other deno starter.
2. To import_map.json add `"yaml": "https://deno.land/x/yaml@v2.1.3/src/public-api.ts",`
3. `deno start task`, it will fail on module resolution

**Expected behaviour**
Source should be compatible with usage as es modules. Alternatively having `dist` committed along with source would probably fix this too though type annotations would be lost then I think.

**Versions (please complete the following information):**

- Environment: deno 1.28.1
- `yaml`: https://deno.land/x/yaml@v2.1.3/src/public-api.ts?source

**Additional context**
Deno does have a yaml parser in its std lib, but it reorders arrays which is not nice.

**Comment by eemeli** [comment]
This is a duplicate of #301.
