### ISSUE TITLE
Parse/convert regular expression values from/to YAML

### ISSUE THREAD

**Issue by Qualphey** [eemeli/yaml#428]
**Is your feature request related to a problem? Please describe.**
Parsing/converting regexp strings to YAML does some backslash escaping, so it makes it confusing for humans. Not sure of what other string mutations might exist that might affect even regexp behavior.

**Describe the solution you'd like**
Special regexp flag support that would make the parser avoid messing with the string and maybe even wrap it in the standard RegExp object.

**Describe alternatives you've considered**
Alternatively you could explain how the parser might affect regular expression strings and what workarounds might be used.

**Comment by eemeli** [comment]
Have you consulted the docs yet on this? The section on [Writing Custom Tags](https://eemeli.org/yaml/#writing-custom-tags) actually has an example dealing with RegExp values.

**Comment by eemeli** [comment]
A custom tag for RegExp values is now available as a part of [yaml-types](https://github.com/eemeli/yaml-types):

```js
import { parse } from 'yaml'
import { regexp } from 'yaml-types'

const re = parse('!re /fo./g', { customTags: [regexp] })
'foxbarfoo'.match(re) // [ 'fox', 'foo' ]
```
