### ISSUE TITLE
v2 custom tags: outdated doc and/or broken types

### ISSUE THREAD

**Issue by 3bl3gamer** [eemeli/yaml#429]
**Describe the bug**
In the [Writing Custom Tags](https://eemeli.org/yaml/#writing-custom-tags) there is an example:

```js
  stringify(item, ctx, onComment, onChompKeep) {
    ...
    return stringifyString({ value: key }, ctx, onComment, onChompKeep)
  }
```

It worked in v1.10 but in v2.1 it returns type error:

```
Argument of type '{ value: string; }' is not assignable to parameter of type 'Scalar<unknown>'.
  Type '{ value: string; }' is missing the following properties from type 'Scalar<unknown>': toJSON, clone, [NODE_TYPE]
```

**To Reproduce**

Create custom tag with

```js
  stringify(item, ctx, onComment, onChompKeep) {
    return stringifyString({ value: 'test' }, ctx, onComment, onChompKeep)
  }
```

**Expected behaviour**

No error.

**Versions:**

- Environment: Node: 19.1.0
- `yaml`: yaml: 2.1.3

**Comment by eemeli** [comment]
Thank you for reporting this! The argument's type was indeed a bit too strict. This wasn't caught by the tests for custom types, as they are (still) JS rather than TS.

I've also made the examples in the docs a little bit more robust.
