### ISSUE TITLE
Markdown mistaken for alias

### ISSUE THREAD

**Issue by ryanmurakami** [eemeli/yaml#437]
**Describe the bug**
Using markdown asterisks to bold a word is being interpreted incorrectly as an alias. Since there's no preceding anchor, this library is throwing an `Unresolved alias` error. 

**To Reproduce**
This code will replicate the behavior:
```js
const yaml = require('yaml');

const input = `
    comment: "this is how to bold:
    **bold text**"
    `;
const docs = yaml.parseAllDocuments(input);
// Unresolved alias error thrown below
const jsDocs = docs.map(doc => doc.toJS());
```

**Expected behaviour**
Markdown inside of quotes shouldn't be interpreted as aliases. Otherwise, if there's a way to disable alias processing during `doc.toJS()`, I could just turn them off.

**Versions (please complete the following information):**

- Environment: Node.js 16
- `yaml`: 2.2.1

**Additional context**
We don't have much control over the incoming yaml, so hoping for a solution or bugfix that won't require modifying the yaml.

**Comment by eemeli** [comment]
In this case, you do need to modify the YAML as it's invalid; the "quoted" value's second line is not more indented than its parent, which is leading to rather broken parsing of the rest of the doc.

You should also check your `doc.errors` array, as that includes this:
```
  YAMLParseError: Missing closing "quote at line 2, column 35:

      comment: "this is how to bold:
                                    ^
```

**Comment by ryanmurakami** [comment]
Oh, I think I understand. The missing closing quotes is causing the next line to be interpreted independently of the quotes. Got it. Thanks for the response!
