### ISSUE TITLE
`this` is not actually the object containing the property being processed in reviver

### ISSUE THREAD

**Issue by SIGSTACKFAULT** [eemeli/yaml#439]
**Describe the bug**
`this` is not actually supplied as context for reviver; it's just `undefined`

**To Reproduce**
```
parse("foo: {bar: baz}", (key, value)=>{
  console.log("reviver", this, key, value)
  return value
})
```

**Expected behaviour**
> The reviver is called with the object containing the property being processed as this

\- [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse#the_reviver_parameter)

**Versions**
- Environment: Node 19
- `yaml`: 2.2.1

**Comment by eemeli** [comment]
You callback function uses fat-arrow notation, where `this` is determined by the enclosing context: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#arrow_functions

Use `function(key, value) { ... }` to access the appropriate `this`.
