### ISSUE TITLE
Unable to get values for nested paths

### ISSUE THREAD

**Issue by imjaadFRT** [eemeli/yaml#440]
**Describe the bug**
I have YAML code that looks like this. 

<img width="329" alt="image" src="https://user-images.githubusercontent.com/83271215/216355412-ad4060e3-d4cc-45dd-bba2-d3055078a771.png">

I am trying to get values at specific paths by using the below code. 
```
const lineCounter = new LineCounter();
const doc = parseDocument(data, { lineCounter });
const node = doc.getIn(["View", "Column", "children"], true);
console.log(lineCounter.linePos(node.range[0])); 
```
output: {col:7, line:11}

this works fine and I'm able to get the line number and column number successfully. But when I try to go deeper and access items after **children**. I am always getting **undefined**.

Here's the code I am using to access the children. 
```
const node = doc.getIn(["View", "Column", "children", "Text"], true);
console.log(lineCounter.linePos(node.range[0]));
```
output: undefined

Correct me if something's wrong here or there is any issue with paths. 
Thank you.

**Comment by eemeli** [comment]
The node at `["View", "Column", "children"]` in your example is a sequence, not a map, so its `"Text"` doesn't exist.

**Comment by imjaadFRT** [comment]
@eemeli can you help with a code snippet how can I access nested values or children in this case.
