### ISSUE TITLE
Newlines in multi-line sequences disappear

### ISSUE THREAD

**Issue by nindoja** [eemeli/yaml#447]
**Describe the bug**
When parsing a multiline sequence, newlines in that sequence get removed from the object's `source` and `value` members. The use case is modifying GitLab CI yaml files, so the objective is to read->modify->write the yaml file with minimal changes to make diffs easy to review.

**To Reproduce**
To reproduce, run the following Javascript: 
```
var yaml = require("yaml")

var gitlab_yml = `
.foo:
  before_script:
    - if [ -z AUDIT ]; then
        echo No AUDIT_ID...;
        export NO_AUDIT=1;
      else
        echo FOUND AUDIT;
        echo DOING OTHER THINGS;
      fi
    - ./process_audit.sh

`

parsed = yaml.parseDocument(gitlab_yml)
yaml.stringify(parsed)
```

1. Note the missing  newlines in the output: 
```
.foo:
  before_script:
    - if [ -z AUDIT ]; then echo No AUDIT_ID...; export NO_AUDIT=1; else echo
      FOUND AUDIT; echo DOING OTHER THINGS; fi
    - ./process_audit.sh

```
**Expected behaviour**
I would expect the output of `yaml.stringify(parsed)` to be the following (in this case, unmodified since the reproduction doesn't have the modification code present):

```
.foo:
  before_script:
    - if [ -z AUDIT ]; then
        echo No AUDIT_ID...;
        export NO_AUDIT=1;
      else
        echo FOUND AUDIT;
        echo DOING OTHER THINGS;
      fi
    - ./process_audit.sh

```

**Versions (please complete the following information):**

- Environment: Node.js 18.6.0
- `yaml`: 2.2.1

**Additional context**
I tried a few different options for both parsing and toString, but nothing seemed to produce the intended output. I could force multi-line output by specifying a low `lineWidth` value, but that doesn't really work since it results in unnecessary changes to the yaml file. Specifying `keepSourceTokens` when parsing the document lets me see that the newlines are present at some point during parsing.

**Comment by eemeli** [comment]
If the newlines are significant, you should probably `|` quote the value:

```yaml
.foo:
  before_script:
    - |
      if [ -z AUDIT ]; then
        echo No AUDIT_ID...;
        export NO_AUDIT=1;
      else
        echo FOUND AUDIT;
        echo DOING OTHER THINGS;
      fi
    - ./process_audit.sh
```

With the plain construction that you're using, the only way to maintain the newlines would be to use the library's CST API: https://eemeli.org/yaml/#parser

**Comment by eemeli** [comment]
That seems unfortunate. Using plain syntax for scalars that include code is pretty risky. For instance, anything that includes a colon `:` followed by white space will lead to a parsing error.

**Comment by eemeli** [comment]
Closing, as there isn't really anything actionable here.
