### ISSUE TITLE
Return first matching alias node

### ISSUE THREAD

**Issue by MikeRalphson** [eemeli/yaml#450]
**Describe the bug**
This aspect of the YAML mediatypes draft is not implemented yet.

https://github.com/ietf-wg-httpapi/mediatypes/blob/0d2cef8bf8e658b2d34ac8e48c3ff999ca827305/draft-ietf-httpapi-yaml-mediatypes.md?plain=1#L153-L154

> If multiple nodes would match a fragment identifier, the first such match is selected.

**To Reproduce**
n/a - can create a repro case if required.

**Expected behaviour**
If multiple nodes match a given fragment identifier, the first such match must be selected.

**Versions (please complete the following information):**

- Environment: Node.js v18.15.0
- `yaml`: v2.2.1

**Comment by eemeli** [comment]
This solution is currently available:
```js
import { parseDocument, visit } from 'yaml'

function findFirstAnchor(doc, anchor) {
  let found = undefined
  visit(doc, {
    Node(_key, node) {
      if (node.anchor === anchor) {
        found = node
        return visit.BREAK
      }
    }
  })
  return found
}

const doc = parseDocument(`
  one: &a 42
  two: &a 13
`)
findFirstAnchor(doc, 'a')
// Scalar { value: 42, type: 'PLAIN', anchor: 'a', ... }
```

@MikeRalphson Would that work for you, or do you think that this needs some built-in solution?

**Comment by MikeRalphson** [comment]
That will definitely work for me, but to save others hunting for a solution if the mediatype RFC gets traction, could it possibly go into core?

**Comment by eemeli** [comment]
It might make sense to add this as an example somewhere, but I'd really rather not add it to the core; the main reason why `visit()` is provided in the first place is to make it as straightforward as possible to implement things in user code.
