### ISSUE TITLE
stringify option to disable alias in output

### ISSUE THREAD

**Issue by yene** [eemeli/yaml#460]
**Is your feature request related to a problem? Please describe.**
hi, thanks for the useful library. I use it to generate pipeline definition YAML.
Sadly the do not accept alias syntax in YAML.

**Describe the solution you'd like**
A way to disable alias in the output

**Describe alternatives you've considered**
I am doing some workarounds but sometimes it seems to automatically detect duplicate content and create alias to it.

**Additional context**
thank you for your time

**Comment by eemeli** [comment]
The option you're looking for is `aliasDuplicateObjects`, see here: https://eemeli.org/yaml/#createnode-options

**Comment by yene** [comment]
Thanks
