### ISSUE TITLE
Performance regression with each new release

### ISSUE THREAD

**Issue by dreamsavior** [eemeli/yaml#461]
First of all, thank you for your hard work all.

I would like to report a performance regression that I have observed while developing my software. Although it may not be considered a bug in the strict sense, it is impacting the performance of my application significantly.

The following is a real live case, when my app is parsing, seeking and manipulating yaml data using yaml API for 200+ yaml files of varying size:

1.10.2 = 59593ms
2.0.0-4 = 65606ms
2.0.0-5 = 132720ms
2.0.0-9 = 136034ms
2.0.0 = 142407ms
2.2.1 = 141100ms

As you can see the biggest jump of performance regression is from version 2.0.0-4 to version 2.0.0-5 which almost double the execution time.

In several occasions, we have observed that the execution of a large YAML file can exceed 2 hours. Additionally, I have heard from one of our users that they have reported a 6-hour execution time.

**Describe the bug**
The performance of the library is regressing with each new release, with the most significant regression occurring between versions 2.0.0-4 and 2.0.0-5. This regression is causing significant delays in the execution of our application, and we are concerned that it may be impacting other users as well.

**Expected behaviour**
While we appreciate new features and critical bug fixes, significant performance regressions are generally not desirable. It is our hope that this issue can be resolved so that we can continue to utilize the library in our software with improved performance.

Thank you for your hard work, and please let me know if you need any further information.

**Comment by eemeli** [comment]
The main focus of `yaml` has at least thus far been to focus on power over performance, and the v2 update was a pretty thorough rewrite of the parsing code, which had become rather convoluted.

While I appreciate that you're observing a change in your metrics, the information you've provided so far isn't really actionable in any way. If you're looking for someone else to be inspired to do something, at a minimum something like a minimal reproduction would be required, so that your benchmarks could be used to determine where the time is being spent with your usage pattern.

On the other hand, if you're interested yourself in improving the library's performance, then PRs to that effect would of course be welcome.

**Comment by dreamsavior** [comment]
@eemeli 
Make sense.
I have created a simple benchmark test for the YAML library to measure the execution time of several YAML APIs hundreds or thousands of times. I hope this can provide useful information for the future development of the library.

You can find the benchmark script here: https://github.com/dreamsavior/yaml-lib-benchmark

I have also tested several releases of the library and obtained the following results:

```shell
Testing YAML version 1.10.2
Working on file :  ./sample/Map002.yaml
File size :  389684 byte
Number of node :  36736
Test 1: parseDocument() x  [ 200 ]
Process took 37688.797500133514 ms.

Test 2: getIn() x  [ 5000 ]
Process took 13.887900114059448 ms.

Test 3: setIn() x  [ 5000 ]
Process took 21.287299871444702 ms.

Test 4: run ToString() x  [ 200 ]
Process took 17124.344799995422 ms.

Test 5: run toJSON() x  [ 200 ]
Process took 767.1546001434326 ms.

Total execution: 55615.47210025787 ms
```
```shell
Testing YAML version 2.0.0-4
Working on file :  ./sample/Map002.yaml
File size :  389684 byte
Number of node :  36736
Test 1: parseDocument() x  [ 200 ]
Process took 54627.61640000343 ms.

Test 2: getIn() x  [ 5000 ]
Process took 18.746700048446655 ms.

Test 3: setIn() x  [ 5000 ]
Process took 23.632800102233887 ms.

Test 4: run ToString() x  [ 200 ]
Process took 20675.565900087357 ms.

Test 5: run toJSON() x  [ 200 ]
Process took 1345.8725001811981 ms.

Total execution: 76691.43430042267 ms
```

```shell
Testing YAML version 2.0.0-5
Working on file :  ./sample/Map002.yaml
File size :  389684 byte
Number of node :  36736
Test 1: parseDocument() x  [ 200 ]
Process took 79710.10039997101 ms.

Test 2: getIn() x  [ 5000 ]
Process took 21.77369999885559 ms.

Test 3: setIn() x  [ 5000 ]
Process took 29.244400024414062 ms.

Test 4: run ToString() x  [ 200 ]
Process took 14725.957900047302 ms.

Test 5: run toJSON() x  [ 200 ]
Process took 52459.54200005531 ms.

Total execution: 146946.6184000969 ms
```

```shell
Testing YAML version 2.2.1
Working on file :  ./sample/Map002.yaml
File size :  389684 byte
Number of node :  36736
Test 1: parseDocument() x  [ 200 ]
Process took 77129.78080010414 ms.

Test 2: getIn() x  [ 5000 ]
Process took 14.584700107574463 ms.

Test 3: setIn() x  [ 5000 ]
Process took 23.482500076293945 ms.

Test 4: run ToString() x  [ 200 ]
Process took 12966.855200052261 ms.

Test 5: run toJSON() x  [ 200 ]
Process took 49244.08389997482 ms.

Total execution: 139378.7871003151 ms
```
With a quick glance, these numbers tell us which version and which api need more optimization.

I hope this information is helpful.

Regards.

**Comment by eemeli** [comment]
Ok, I see that your benchmark is measuring parsing and/or emitting of a 380kB YAML file as taking a few hundred ms, while get/set operations are measured in microseconds.

With most usage patterns, these operating speeds are plenty sufficient, so it's a bit surprising that in your case they're leading to execution times in hours. At least on my machine, parsing and stringifying all of the 208 files totaling 19MB in your sample directory takes in total a bit under 6 seconds, which is about three orders of magnitude less than your execution times.

Now, what is your expectation for what should happen next here? As I mentioned previously, if you're interested yourself in improving the library's performance, then PRs to that effect would of course be welcome. On the other hand, your benchmarks are not pointing out to me any one specific improvement that seems worthwhile for me to work on; there's a lot going on during the parse, for instance: https://eemeli.org/yaml/#parsing-yaml

**Comment by eemeli** [comment]
Closing, as there doesn't appear to be anything actionable here.
