### ISSUE TITLE
`allOf` with condition breaks completion

### ISSUE THREAD

**Issue by EmilySeville7cfg** [eemeli/yaml#462]
**Describe the bug**
While choosing suggested property value, `Tab` inserts `<property-value>: <property-value>` instead of just `<property-value>`:

![image](https://user-images.githubusercontent.com/42812113/230767692-4b4cad9f-6da3-4ba7-b30c-4c13876b3c5e.png)

**To Reproduce**
Setup:

```json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "definitions": {
        "version-property": {
            "description": "A syntax version\nhttps://taskfile.dev/usage/#getting-started",
            "type": "string",
            "enum": [
                "2"
            ]
        },
        "v2-properties": {
            "properties": {
                "version": {
                    "$ref": "#/definitions/version-property"
                }
            },
            "additionalProperties": false
        }
    },
    "title": "tasks",
    "description": "Tasks",
    "type": "object",
    "required": [
        "version"
    ],
    "properties": {
        "version": {
            "$ref": "#/definitions/version-property"
        }
    },
    "allOf": [
        {
            "if": {
                "properties": {
                    "version": {
                        "const": "2"
                    }
                }
            },
            "then": {
                "$ref": "#/definitions/v2-properties"
            }
        }
    ]
}
```

schema for some local YAML file via **.vscode/settings.json**

Try to complete `version` value and obtain this bug.

**Expected behaviour**
Just `"2"` expected to be put while `2: 2` is inserted.

**Versions (please complete the following information):**

- Environment: Node.js 16.14.2
- `yaml`: [e.g. 1.10.0 or 2.0.0-2]
- OS: Linux x64 5.15.0-67-generic

**Additional context**

**Comment by eemeli** [comment]
Wrong repo for this; your issue appears to be with your VS Code plugin.
