### ISSUE TITLE
Can yaml with comments be converted to properties and properties with comments be converted to yaml format?

### ISSUE THREAD

**Issue by Ximeng0918** [eemeli/yaml#472]
**Is your feature request related to a problem? Please describe.**
Yes, I'm looking for a solution to convert yaml files containing comments to properties files with comments, and vice versa.

**Describe the solution you'd like**
I would like to see support for converting yaml files containing comments to properties files with comments, and vice versa. This would be a useful feature for managing and updating properties files with comments, and vice versa. It would be great if this feature could be added to the existing software.

**Describe alternatives you've considered**
I have considered manually converting the files, but this is time-consuming and error-prone. I have also searched for existing tools that can do this, but have not found anything that fits my needs so far.

**Additional context**
I am currently using the software for managing properties files, but I also have some yaml files that contain comments and are used for other purposes. It would be great if I could easily convert these files back and forth between yaml and properties file formats with their respective comments intact.

**Comment by eemeli** [comment]
See [eemeli/dot-properties](https://github.com/eemeli/dot-properties) for a `.properties` parser & stringifier that's capable of handling comments. Using that you should be able to put together a conversion tool relatively easily.

**Comment by Ximeng0918** [comment]
Before submitting this issue, I was researching your dot-properties project, and I was thinking of combining it with your yaml project to create a conversion tool. I thought that both of these projects were developed by you, so I wanted to ask if you have already implemented a similar functionality. If not, I will study and combine them myself. Thank you for your projects.
