### ISSUE TITLE
npm install failed in engine strict mode for npm >=7 check

### ISSUE THREAD

**Issue by swarnadeepsaha** [eemeli/yaml#476]
**Describe the bug**
In this [change](https://github.com/eemeli/yaml/commit/78549261941e0efc4b98a5a7db63cd42acf0545e)
npm engine >=7 create an issue where npm >=6.14 <7.

**To Reproduce**
- node 14 minimum requirements (*npm is >=6.14*) with `engine-strict=true`.
https://nodejs.org/en/download/releases
- Or install node 14 using the *node version manager*(`nvm`) tool with `engine-strict=true`.

`npm install` will fail with:
```
npm ERR! code ENOTSUP
npm ERR! notsup Unsupported engine for yaml@2.3.0: wanted: {"node":">= 14","npm":">= 7"} (current: {"node":"14.20.0","npm":"6.14.17"})
npm ERR! notsup Not compatible with your version of node/npm: yaml@2.3.0
npm ERR! notsup Not compatible with your version of node/npm: yaml@2.3.0
npm ERR! notsup Required: {"node":">= 14","npm":">= 7"}
npm ERR! notsup Actual:   {"npm":"6.14.17","node":"14.20.0"}
```

**Expected behavior**
npm >= 6.14, not npm >= 7

**Versions:**
- Environment: Node.js 14.20.0
- `yaml`: 2.3.0

**Comment by eemeli** [comment]
That's a bit unfortunate, as npm v7 is required for the build. Guess we'll need to drop it from the engines config.

I would also encourage you to consider updating your environment, as Node.js v14 has reached its end of life.

**Comment by swarnadeepsaha** [comment]
> That's a bit unfortunate, as npm v7 is required for the build. Guess we'll need to drop it from the engines config.
> 
> I would also encourage you to consider updating your environment, as Node.js v14 has reached its end of life.

Yes, node upgrade is on the list too.
Thanks @eemeli for the quick response.
