### ISSUE TITLE
Should a basic CLI be included?

### ISSUE THREAD

**Issue by eemeli** [eemeli/yaml#479]
I'm considering adding a command-line interface for `yaml`. Something pretty basic, and reliant on the Node.js [util.parseArgs](https://nodejs.org/api/util.html#utilparseargsconfig) that was added in v16, and is no longer experimental in v20.

Is this something that you might find useful? If so, how minimal could it be in order to be useful? Reactions and comments here would be helpful.

**Comment by danielbayley** [comment]
@eemeli Definitely! I think, amongst other things, it should include aliases to seamlessly replace `yaml2json` and `json2yaml` that [come with](https://github.com/jeremyfa/yaml.js/blob/develop/package.json#L22-L25) _[yamljs](https://github.com/jeremyfa/yaml.js#readme)_, making replacing that library with this (better one) easier…

**Comment by antonmedv** [comment]
@eemeli thanks for an awesome library! I really like it, the code is clean, and no dependencies ❤️

The cli definitely should be added. Especially if by default it will output JSON, so it can be piped to [fx](https://www.npmjs.com/package/fx) package:

```bash
cat config.yaml | npx yaml | npx fx .values
```

**Comment by eemeli** [comment]
> I can submit a PR if this behavior is okay :)

Yeah, let's start with that. A command that takes no arguments, parses its standard input as a single document and produces JSON at its standard output.

If you do feel like adding arguments, then I think `strict` and `schema` could be considered initially, but probably no others.
