### ISSUE TITLE
Provide a browser version that doesn't require ES modules

### ISSUE THREAD

**Issue by nt1m** [eemeli/yaml#480]
Right now I can do:
```js
import YAML from "https://unpkg.com/yaml@2.3.1/browser/index.js";
```

but that requires me to change existing scripts to be modules.

I'd like to be able to use YAML by just doing:
```html
<script src="..."></script>
```

**Comment by eemeli** [comment]
As this is a source repository that does not package the code for production, what you're asking for is a bit beyond its scope.

You're probably best off by packaging `yaml` yourself in a shape that suits your use case.
