### ISSUE TITLE
Use esbuild and dts-bundle-generator instead of rollup

### ISSUE THREAD

**Issue by Uzlopak** [eemeli/yaml#485]
I think it is worth to investigate if we could use esbuild and dts-bundle-generator instead of rollup to shrink the size of the npm package.

**Comment by eemeli** [comment]
Why should the size of the npm package be shrunk?

**Comment by eemeli** [comment]
Again, why should the size of the npm package be shrunk?

**Comment by indiealexh** [comment]
> Again, why should the size of the npm package be shrunk?

To improve the loading times on mobile devices.

**Comment by eemeli** [comment]
This is a library, and for mobile end users its browser build will be repackaged by applications. For them, the size of the npm package is irrelevant; it only matters what the minified + gzipped size ends up at, a bit under 32kB currently.
