### ISSUE TITLE
Maybe We can add row & col number when parse yaml

### ISSUE THREAD

**Issue by RealKai42** [eemeli/yaml#495]
**Is your feature request related to a problem? Please describe.**
I am developing a vscode plugin for yaml file, and I want to add some CodeLens feature to yaml file. So, I need know the original row&col number from the parsed yaml obj.

**Describe the solution you'd like**
get the start and end row & col number of each property of parsed yaml obj.

If it's hard to add this feature, is there any hack way to get it?

**Comment by lockiechen** [comment]
I also have such a need, what should I do?

**Comment by eemeli** [comment]
I'd suggest you search for `lineCounter` in the docs, it should provide what you need: https://eemeli.org/yaml

**Comment by sweetpalma** [comment]
@eemeli I spent some time reading documentation and experimenting - but I'm still not able to overcome this issue. What I'm trying to do is to convert [Zod](https://zod.dev) validation error path that looks `like[0].this` into a specific line and column where the given property is defined in YAML. 

Only solution I found so far is traversing down the `Document` using given path, but that requires a lot of code which is hard to understand. Is there any easier way to do this? Thanks!

**Comment by eemeli** [comment]
@sweetpalma Which part more specifically are you finding to need "a lot of code which is hard to understand"?

1. Parse the doc with a LineCounter.
2. Find the node for a given path.
3. Map its position to row/column coordinates.

**Comment by sweetpalma** [comment]
@eemeli oh, seems like I missed the `doc.getIn` part of the documentation. Feeling so silly right now... So for anybody else struggling with this, here's an example of the code:

```typescript
import { parseDocument, isNode, Document, YAMLError, LineCounter } from 'yaml';
import zod, { ZodIssue } from 'zod';

export const ParserSchema = zod.object({
  // some schema
});

export class Parser {
  public parse(source: string) {
    const lineCounter = new LineCounter();
    const doc = parseDocument(source, { lineCounter });
    if (doc.errors.length > 0) {
      const mainError = doc.errors[0]!;
      throw this.formatErrorYml(mainError, lineCounter);
    }

    // Validate data.
    const validationResult = ParserSchema.safeParse(doc.toJS());
    if (!validationResult.success) {
      const mainError = validationResult.error.issues[0]!;
      throw this.formatErrorZod(mainError, lineCounter, doc);
    }

    // Do stuff with the parsed document
    // ...
  }

  /**
   * Format `zod` error using document line counter and metadata.
   */
  private formatErrorZod(err: ZodIssue, lc: LineCounter, doc: Document) {
    const node = doc.getIn(err.path, true);
    if (isNode(node) && node.range) {
      const { line, col } = lc.linePos(node.range[0]);
      return new Error(`${line}:${col} ${err.message}`);
    } else {
      return new Error(err.message);
    }
  }

  /**
   * Format `yml` error using document line counter.
   */
  private formatErrorYml(err: YAMLError, lc: LineCounter) {
    const { line, col } = lc.linePos(err.pos[0]);
    return new ParserError(`${line}:${col} ${err.message}`);
  }
}
```
