### ISSUE TITLE
Yaml parse error when parsing array with curly braces.

### ISSUE THREAD

**Issue by maxco2** [eemeli/yaml#496]
**Describe the bug**
Yaml parse error when parsing array with curly braces.

**To Reproduce**
````js
var yaml = require("yaml")
yaml.parse(`
- foo: {
  bar: boom
}
`);
````

Got a syntax error,

> YAMLParseError: Flow map in block collection must be sufficiently indented and end with a } at line 3, column 3:
> 
> - foo: {
>   bar: boom
>   ^

**Expected behaviour**
No error.

**Versions (please complete the following information):**

- `yaml`: 2.3.2

**Additional context**

You can reproduce it in runkit: https://runkit.com/embed/4zxk0x9y2b3d

**Comment by eemeli** [comment]
As the error suggests, your trailing brace `}` is not sufficiently indented.
