### ISSUE TITLE
Cannot find `mapAsMap` option

### ISSUE THREAD

**Issue by garysassano** [eemeli/yaml#500]
**Describe the bug**
```
(node:1411631) Warning: Keys with collection values will be stringified due to JS Object restrictions: "{ content }". Set mapAsMap: true to use object keys.
```

**To Reproduce**
Steps to reproduce the behaviour.

**Expected behaviour**

**Versions (please complete the following information):**

- Environment: [e.g. Node.js 14.7.0 or Chrome 87.0]
- `yaml`: [2.3.2]

**Additional context**

**Comment by eemeli** [comment]
Closing due to incomplete information.
