### ISSUE TITLE
Reported type in vscode is possibly wrong

### ISSUE THREAD

**Issue by wtfacoconut** [eemeli/yaml#503]
**Describe the bug**
I'm currently using this library in a new SvelteKit project with TypeScript.
The easiest way for me to explain the bug is with a code snippet of my code:
```
function printParsedYaml(){
  if(yamlSrcCode){
	  let tmpObj: Document = parseDocument(yamlSrcCode); 
	  let tmpItems: YAMLMap = tmpObj.contents; // vscode is wrong for some reason contents is of type YAMLmap, not Node. I checked the constructor name in chrome console, and it's YAMLMap
	  console.log(tmpObj.contents.items); // Because of the above issue, vscode things the items property doesn't exist
	  console.log(tmpItems.items);
  } else{
	  console.log("No src to parse.");
  }
}
```

**To Reproduce**
Please see the code snippet above

**Expected behaviour**
That vscode would report the correct return type

**Versions (please complete the following information):**
- Node.js: 18.17.1
- yaml: 2.3.3
- vscode: 1.84..0

**Comment by eemeli** [comment]
How do you propose for the TS tooling to know that your YAML source represents a map?

**Comment by wtfacoconut** [comment]
Hey @eemeli. I'm new to using this library (and new to JS/TS), so thanks for the speedy reply.
Based on you response, I'm guessing for any given node, the library does not determin the node's type (eg: YAMLMap, YAMLSeq, Scalar or null) until it is parsed at runtime. Is my understanding correct? 

I guess because I didn't notice anything with the feedback from intellisense, this went over my head. 
![image](https://github.com/eemeli/yaml/assets/5297545/561a1692-f1b2-4b61-865a-dbfd7b92925b)

Maybe the description for the contents property could be updated to say something like:
```
The document contents. At runtime, the document node type will be of type YAMLMap, YAMLSeq, Scalar or null.
```

The only section in the library's documentation that looks like it mentions this is at the bottom of the section for `creating documents` [https://eemeli.org/yaml/#creating-documents](link)
![image](https://github.com/eemeli/yaml/assets/5297545/60d09de1-2bb6-433e-9c0a-9d53316cf4e5)

Again, I'm new to using this library and I'm not knowledgable when it comes to things like parsers, so thanks for bearing with me. I highly suspect what I'm pointing out is a non-issue and is just something that people who typically use parsers in the JS/TS world understand as a convention (or something along those lines).

**Comment by eemeli** [comment]
This is not a `yaml` library issue at all; you're hitting a fundamental restriction in the static typing of TS.

**Comment by wtfacoconut** [comment]
Hey @eemeli . Thanks for the confirmation. I was starting to feel my issue was something along the lines of what you mentioned.

What would you thoughts be if I submitted a small PR to update the intellisense documentation to something like this?
![image](https://github.com/eemeli/yaml/assets/5297545/b798113c-de92-4724-b8df-62cd265b4d7a)

Again, for me at least, I felt it wasn't immediately obvious what the `yaml` library's behavior was, so maybe this small documentation update will be helpful? What do you think?

**Comment by eemeli** [comment]
That would be what the default value of the `Contents` parametric type is, so the addition would be duplicating that information:
https://github.com/eemeli/yaml/blob/b7696fc001837a2e9d66ad78d7c04f47943daeca/src/nodes/Node.ts#L13-L17

**Comment by wtfacoconut** [comment]
Agreed that this would be a duplication, but nothing was popping up with vscode intellisense to even hint that `Node` could be those other types. If you're just starting to use the library, I think the natural inclination for people would be to first see the feedback from intellisense. Otherwise, the only way that you'll know about this is to experiment or directly look at `Node's` type def.

I created PR #504 anyways. Feel free to reject if you feel it isn't worth it, but as someone who's new to this, the extra context from intellisense would have been a "nice to have" thing.
