### ISSUE TITLE
Wrong output of `stringify` if multiple fields is same `Date` instance

### ISSUE THREAD

**Issue by li-yechao** [eemeli/yaml#508]
**Describe the bug**
Wrong output of `stringify` if multiple fields is same date instance

**To Reproduce**
1. js
```
const date = new Date();
console.log(stringify({ date, date1: date }));
```
3. output
```
date: &a1 2023-12-05T14:47:24.422Z
date1: *a1
```

**Expected behaviour**
should output
```
date: 2023-12-05T14:47:24.422Z
date1: 2023-12-05T14:47:24.422Z
```

**Versions (please complete the following information):**

- Environment: v21.2.0
- `yaml`: 2.3.1

**Additional context**

**Comment by eemeli** [comment]
Given that YAML supports `*aliases` in part to allow the representation of identical objects as the same, the current behaviour is the safest way to guarantee that such identity is retained when representing the data as YAML. Changing the default value of the option would also be a breaking change.
