### ISSUE TITLE
!!omap support (or not?)

### ISSUE THREAD

**Issue by fabiospampinato** [eemeli/yaml#520]
**Describe the bug**

I'm reading YAML's [changelog](https://yaml.org/spec/1.2.2/ext/changes/#:~:text=The%20!!pairs%2C%20!!omap%2C%20!!set%2C%20!!timestamp%20and%20!!binary%20types%20have%20been%20dropped.), and according to it support for the `!!omap` type has been dropped in v1.2.

So I'd expect it to not be supported in a v1.2 compliant parser.

**To Reproduce**

The following code gives me an ordered map, as if `!!omap` never got dropped:

```ts
import yaml from 'yaml';

const result = yaml.parse(`--- !!omap
- Mark McGwire: 65
- Sammy Sosa: 63
- Ken Griffy: 58
`, {
  version: '1.2'
});

console.log ( result );
```

**Expected behaviour**

I'd probably expect that code to throw?

**Versions (please complete the following information):**

- Environment: Node v18.19.0
- `yaml`: v2.3.4

**Additional context**

Looking at the [spec](https://yaml.org/spec/1.2.2/) for v1.2.2 there's actually an example snippet of code that seems to imply that `!!omap` is still supported, but that's literally the only reference to "omap" in the entire document.

![Screen Shot 2024-02-08 at 18 41 36](https://github.com/eemeli/yaml/assets/1812093/13ff4059-b479-4d81-8a34-93617eb70f18)

So I'm pretty confused about this. Should `!!omap` still be supported in v1.2 or not? And whatever the answer is how did we arrive at that? Because I'm seeing contrasting information.

**Comment by eemeli** [comment]
If you'd rather not have the YAML 1.1 tags recognised when used explicitly, you may set `resolveKnownTags: false` when parsing: https://eemeli.org/yaml/#schema-options

**Comment by fabiospampinato** [comment]
I see. Is that the only other option needed to get a spec-compliant v1.2 parser?

**Comment by eemeli** [comment]
The parser is by default 1.2 spec-compliant, and for all untagged content it follows the Core Schema, as recommended by the spec. For explicit tags, we follow the advice in the [Other Schemas](https://yaml.org/spec/1.2.2/#104-other-schemas) section,
> None of the above recommended schemas preclude the use of arbitrary explicit tags.

and represent e.g. the JS `Map` as `!!omap`, `Set` as `!!set`, `Date` as `!!timestamp`, and `Uint8Array` as `!!binary`, using their YAML 1.1 definitions (given that those are well defined and more interoperable than any alternative). Tags for JS values that are not well represented by the YAML 1.1 type definitions are available separately via the [`yaml-types`](https://github.com/eemeli/yaml-types) package.
