### ISSUE TITLE
Indentation of array elements is not standard

### ISSUE THREAD

**Issue by atombender** [eemeli/yaml#53]
Block sequences (ie., arrays) need not be indented. As the [1.1 spec says](http://yaml.org/spec/1.1/#id931893), the dash is *considered part of the indentation*. So this is the correct, idiomatic way of representing arrays:

``` yaml
array:
- one
- two
- three
```

The 1.2 spec does not explain this very well (it's not very well written as specs go), but this is the style used on the [current yaml.org front page](http://yaml.org/).

The current serialization adds one indentation level too many:

``` yaml
array:
  - one
  - two
  - three
```

This is admittedly a frequent point of confusion among YAML users; some people do indent. But as evidence of implementations that do it right, look at Ruby's standard `yaml` library. At least there should be a configuration option.

**Comment by eemeli** [comment]
The most active public discussion on this can be found at prettier/prettier#4723, which indicated a clear preference for indentation. My gut feeling is that making this configurable would be more effort than it's worth -- YAML has plenty of corner cases where a change like this will trip you up.

However, if you're interested in putting together a PR I'd be willing to consider it. Probably the best place to start would be fiddling with the [`Collection`](../blob/master/src/schema/Collection.js) stringifier. Our test suite should be pretty good at catching most of the errors there.

**Comment by atombender** [comment]
I wouldn't put much faith in random Internet polls by people I don't know, and Prettier has its share of [irrational decisions](https://github.com/prettier/prettier/issues/1985).

I'll see if I'll have time to make a PR. For now, I've switched to a different YAML library that does what I want.

**Comment by eemeli** [comment]
I'm closing this, but would still be interested to later consider a PR for making the indenting behaviour optional. The right API for that would probably be via an `options` object added [here](../blob/master/src/schema/failsafe.js#L15).
