### ISSUE TITLE
Unexpected error for sufficient indentation

### ISSUE THREAD

**Issue by keestux** [eemeli/yaml#539]
**Describe the bug**
An unexpected error is given for sufficient indentation. This comes from a `.gitlab-ci.yml`, GitLab does not complain about it. Also `yq` and `yamllint` don't report an error for this. However the vscode plugin marks it with an error.

I'm assuming that the `redhat.vscode-yaml` plugin is based on this Git repo.

**To Reproduce**
This piece of Yaml
```yaml
---
- BAR: [a,
        b,
]
- FOO: [a, b]
```

vscode with the `redhat.vscode-yaml` plugin gives an error on line 4. All the rest of the yaml is flagged with lots of errors.

**Expected behaviour**
Any indentation on line 4 should be accepted as valid Yaml.

**Versions (please complete the following information):**

- Environment: vscode 
- `redhat.vscode-yaml`: 1.14.0

**Comment by eemeli** [comment]
You example is invalid YAML, due to insufficient indentation of the `]`. This should really be reported by other tools, but even if they don't, it's still wrong.

**Comment by keestux** [comment]
Wow, that's not an answer I expected.

What's your explanation that there are so many "incorrect" implementations? I mean, the ones I checked are not some random hobby projects:
- `yq` (well respected yaml tool)
- GitLab
- various Python yaml libraries
- `yaml-rust`
- JetBrains (CLion)

You can imagine that I cannot just go to any of them and tell them they have an invalid implementation.

BTW The Perl implementation requires at least three spaces on line 4 of my example
```yaml
---
- BAR: [a,
        b,
   ]
- FOO: [a, b]
```
Perl::PP is being tested with `yaml-test-suite` (so they say in there README). If that's true then my test case is not tested.

**Comment by eemeli** [comment]
This is covered at least by this test case, which does indeed show a number of implementations not matching the spec: https://matrix.yaml.info/details/9C9N.html

**Comment by keestux** [comment]
Thanks for the pointer. I'll take a look.
