### ISSUE TITLE
`#comment` parsed as incorrectly indented string in root block-scalar

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#547]
**Describe the bug**
An error occurs when a `#comment` is one outdented than the (root level) block-scalar [indentation-indicator](https://yaml.org/spec/1.2.2/#8111-block-indentation-indicator) indicates
`Block scalar lines must not be less indented than their explicit indentation indicator`

**To Reproduce**
```yaml
abc: |5 # no error
      # string 6
     # string 5
    #comment 4
   #comment 3

---

|5 # error at #comment 4
      # string 6
     # string 5
    #comment 4
   #comment 3
```

**Expected behaviour**
`#comment 4` should be parsed as `comment`, not as part of the multi-line string

**Versions:**

- Environment: VSCode 1.89
- `yaml`: `2.4.2`

**Additional context**
![image](https://github.com/eemeli/yaml/assets/33529441/4e97af2d-075a-4210-890e-a206acd1e359)
![image](https://github.com/eemeli/yaml/assets/33529441/cc187ddb-f1ef-4020-b2e2-68c419674b78)

**Comment by eemeli** [comment]
Yeah, there's something odd going on here. Probably to do with the -1 indent level that unindented nodes are considered to have.
