### ISSUE TITLE
`tab` incorrectly allowed before block sequence

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#549]
**Describe the bug**
[block-collection](https://yaml.org/spec/1.2.2/#rule-s-l+block-collection), [block-sequence](https://yaml.org/spec/1.2.2/#rule-l+block-sequence)
there is no `separator` rule between [s-indent](https://yaml.org/spec/1.2.2/#rule-s-indent) and [c-sequence-entry](https://yaml.org/spec/1.2.2/#rule-c-sequence-entry)

**To Reproduce**
```yaml
	-
```

**Expected behaviour**
an error to be given when there is a `tab` before a block sequence `-`

**Versions:**
- Environment: VSCode `1.89`
- `yaml`: `2.4.3`

**Additional context**
![image](https://github.com/eemeli/yaml/assets/33529441/8f25d7ab-ba78-4b06-9910-06f8817e93e5)

**Comment by eemeli** [comment]
Confirming that this is indeed a bug.
