### ISSUE TITLE
Incorrect parsing of explicit sibling maps

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#551]
**Describe the bug**
explicit sibling maps are parsed as nested

**To Reproduce**
```yaml
?
? abc
```

**Expected behaviour**
output should be two map nodes
first one should be `null: null`
2nd one `abc: null`
[l+block-mapping](https://yaml.org/spec/1.2.2/#rule-l+block-mapping) states children must be indented further and siblings use the same indentation

**Versions:**
- Environment: VSCode `1.89`
- `yaml`: `2.4.3`

**Additional context**
![image](https://github.com/eemeli/yaml/assets/33529441/bd1f33f2-944f-44e2-b19a-9527c5f6ff43)
```yaml
---
!!map { #should be this
  ? !!null "null"
  : !!null "null",
  ? !!str "abc"
  : !!null "null",
}
```

**Comment by eemeli** [comment]
Confirming this as a bug.
