### ISSUE TITLE
Indentation leaking across documents

### ISSUE THREAD

**Issue by RedCMD** [eemeli/yaml#558]
**Describe the bug**
Indentation doesn't seem to get reset correctly across `...` document ends for flow mappings/sequences

**To Reproduce**
```yaml
  a: b

...

{
  c: d
}
```

**Expected behaviour**
No error

**Versions**
- Environment: VSCode `1.90`
- `yaml`: `2.4.5`
- extension: `v1.15.0`

**Additional context**
![image](https://github.com/eemeli/yaml/assets/33529441/b07cfb76-68ea-4a66-9c2c-9866eca4e2a5)

**Comment by eemeli** [comment]
I'm not able to replicate this problem with `yaml@2.4.5` directly, or with the VS Code YAML plugin. Does this show up for you consistently, or is there e.g. some specific sequence of editing steps that produces this error?

**Comment by RedCMD** [comment]
so far its been 100% consistent
just tested in https://insiders.vscode.dev/
installed the YAML extension and typed up a minimal example
```yaml
 :
...
{
}
```
![image](https://github.com/eemeli/yaml/assets/33529441/b20a05ff-7e25-439e-b005-4c8a807eada8)
![image](https://github.com/eemeli/yaml/assets/33529441/e445abce-62c6-45d1-8a88-249522b4fe63)

**Comment by eemeli** [comment]
Ah, now I see it. The snippet you posted earlier has a completely empty line before the `...`, and the bug only shows up if it's preceded by a non-empty line. From the "Alt+F8" part of the tooltip, I gather that you're on Windows, where newlines are encoded as `\r\n`, and the CR is sufficient to make the line non-empty enough for whatever's causing this.

**Comment by RedCMD** [comment]
nice catch

changing the EOL to `LN` does indeed fix it
