### ISSUE TITLE
Add support for regex to not be surrounded by quotes

### ISSUE THREAD

**Issue by joshkotrous** [eemeli/yaml#567]
I am working on a project that requires including unquote regular expressions in the pipeline like so
```
- pattern-regex: .*\b(?i)(select|delete|insert|create|update|alter|drop)\b.*
```

`.*\b(?i)(select|delete|insert|create|update|alter|drop)\b.*`

Because of the line length, I dont think this is being recognized as regex and is being surrounded by quotes:
```
- pattern-regex: ".*\b(?i)(select|delete|insert|create|update|alter|drop)\b.*"
```

 This is breaking the regular expression in the yaml. 

**Describe the solution you'd like**
i reviewed the `stringifyString.ts` file and it appears like it may need support added to check if the input string is valid regex, and if so return a plain string not surrounded by quotes. 

**Describe alternatives you've considered**
I've explored adding replacers to achieve what I need, but I dont think this will work as the issue is with how the field is stringified not the value itself.

**Comment by eemeli** [comment]
Please share a code snippet that shows the issue you're seeing.

**Comment by eemeli** [comment]
Closing due to silence.
