### ISSUE TITLE
Duplicate of https://github.com/eemeli/yaml/issues/105

### ISSUE THREAD

**Issue by billyatroadie** [eemeli/yaml#571]
Wanted to put this in as a new issue, because the old one is closed and wanted to make sure it gets re-visited.
https://github.com/eemeli/yaml/issues/105

**Comment by eemeli** [comment]
Please expand on the actual problem that you're experiencing, and clarify how the answer given in https://github.com/eemeli/yaml/issues/105#issuecomment-479947900 is not sufficient? It's not clear what you're looking for, and what you imagine an acceptable solution looking like.

**Comment by eemeli** [comment]
Closing due to silence.
