### ISSUE TITLE
Ending comments got lost after `stringify`

### ISSUE THREAD

**Issue by longkai** [eemeli/yaml#576]
**Describe the bug**

Do parsing the text then format it.

```js
  let doc = YAML.parseDocument(text);
  console.log(YAML.stringify(doc));
```

**To Reproduce**

input text:

```yaml
a:   1
#a: 1
# b: 2
```

got result:

```yaml
a: 1
```

**Expected behaviour**

```yaml
a: 1
#a: 1
# b: 2

```

**Versions (please complete the following information):**

- Environment: Node.js v22.6.0
- `yaml`: 2.5.1

**Additional context**

None

**Comment by eemeli** [comment]
Technically, the right way to serialize a document would be via `String(doc)` or `doc.toString()`, but adding an affordance for `stringify()` to also do the right thing seemed like the right choice.

**Comment by longkai** [comment]
Thanks a lot!
