### ISSUE TITLE
feature request: cdnjs support

### ISSUE THREAD

**Issue by FeignClaims** [eemeli/yaml#596]
**Is your feature request related to a problem? Please describe.**
I'm willing to dynamically inject this package in `<script>`, but failed to do so.

**Describe the solution you'd like**
would be great to have this repository on [CDNJS](https://github.com/cdnjs/packages/blob/master/CONTRIBUTING.md#creating-a-new-library-on-cdnjs), where js-yaml, yamljs, yaml-js [seems already existing](https://cdnjs.com/libraries?q=yaml).

**Describe alternatives you've considered**
In my use case, I am unable to use npm install because I am simply writing a lightweight script rather than a package. Therefore, if this package cannot meet my needs, I may consider exploring other JavaScript YAML parsing libraries, even though I really appreciate this package's interface consistency with built-in JSON (e.g., `JSON.parse` and `JSON.stringify`).

**Comment by eemeli** [comment]
Why not build it yourself and serve it alongside your script? The answer given here should work for you as well: https://github.com/eemeli/yaml/discussions/589#discussioncomment-11347822.

**Comment by FeignClaims** [comment]
> Why not build it yourself and serve it alongside your script? The answer given here should work for you as well: [#589 (comment)](https://github.com/eemeli/yaml/discussions/589#discussioncomment-11347822).

Got it, thank you! I will give this solution a try.

Additionally, may I submit a feature request to add this package to CDNJS myself? My current use case involves writing script snippets for a specific frontend webpage, where I don’t have access to anything beyond the script itself. As a result, managing a custom script link might be too cumbersome, and my clients may face difficulties using it due to network issues.

![image](https://github.com/user-attachments/assets/e52f6925-61c9-4255-a638-5cad99bd2a08)

**Comment by eemeli** [comment]
Eh, I can't stop you from adding it to CDNJS, but the release isn't really optimal for their automatic build, which appears to not bundle files.

**Comment by FeignClaims** [comment]
> Eh, I can't stop you from adding it to CDNJS, but the release isn't really optimal for their automatic build, which appears to not bundle files.

I see... Thanks for your patience.
