### ISSUE TITLE
Failed to parse empty string

### ISSUE THREAD

**Issue by AkatQuas** [eemeli/yaml#66]
```javascript
import YAML from 'yaml';

YAML.parse('');
```

The above code throws an error. However it should return an empty object `{}` or `null`.

**Comment by eemeli** [comment]
Could you verify the version of `yaml` you're seeing this with? It should work with the latest release, 1.2.0:
```js
YAML.parse('') // null
```

**Comment by AkatQuas** [comment]
Yeah it works.

Thanks a lot! 😁
