### ISSUE TITLE
Define CST (and AST) acronyms in the README

### ISSUE THREAD

**Issue by MikeRalphson** [eemeli/yaml#71]
I was clear about the meaning of AST, but hadn't actually come across the acronym CST before and had to look it up. Possibly linking to [wikipedia](https://en.wikipedia.org/wiki/Parse_tree) (though that isn't a computer-science focussed article) or maybe [here](https://eli.thegreenplace.net/2009/02/16/abstract-vs-concrete-syntax-trees/) might be helpful?

Happy to PR if you think this is worth adding.

**Comment by eemeli** [comment]
Actually, there already is a link to the "Parse tree" Wikipedia page in the intro to the [CST Parser](https://eemeli.org/yaml/#cst-parser) section of the docs, and to "Abstract syntax tree" in the intro of [Content Nodes](https://eemeli.org/yaml/#content-nodes). As the latter isn't necessarily self-evident, I've linked the "AST" mention of the API intro to that section as well.

Now, admittedly those aren't the README, but that I've kept intentionally minimalistic; it's really only got a couple of paragraphs, a few examples, and links into the actual docs. Most users are likely to be happy with just `YAML.parse()` and/or `YAML.stringify()`, so it doesn't really make sense to subject them to implementation details.

@MikeRalphson If you still think the terms should be more clearly explained, would you have any specific suggestions for what you'd change?

**Comment by MikeRalphson** [comment]
No, I think that's enough. This issue itself will also show up when searching for 'CST'. Thanks.
