### ISSUE TITLE
Classes in bundled code breaks IE11 compatibility

### ISSUE THREAD

**Issue by ViggoV** [eemeli/yaml#72]
I've been having a real hard time debugging an issue with IE11 and it turns out the offending party is `yaml`, since your babel config apparently doesn't transform classes. Is there a special reason for this? I was surprised since it's the first dependency I've come across with this issue. 80% of our customers use IE11 (yeah, I know 🙄) so It's hard to ignore.

Anyway, I'll just write out `yaml` for now. Thank you for an otherwise great library.

**Comment by eemeli** [comment]
This is caused by only having Node 6 as our babel transpilation target, and not having really tested the library in browsers yet. I'm actually working on the targets just now; `yaml` should relatively soon get a "browser" field in its package.json for client-side use.
