### ISSUE TITLE
Default vs match for custom scalars

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#80]
I'm currently using this as my Symbol type:

```js
const stringType = require('yaml/dist/schema/_string.js')
module.exports = {
  class: Symbol,
  tag: 'tag:node-tap.org,2019:symbol',
  resolve (doc, $1) {
    return Symbol($1)
  },
  test: /^Symbol\((.*)\)$/,
  stringify (item, ctx, onComment, onChompKeep) {
    return stringType.stringify(item, ctx, onComment, onChompKeep)
  },
}
```

I notice that the results are always double-quoted:

```js
{
  a: Symbol(a),
  b: 'Symbol(b)'  // not actually symbol, just matches the regexp
}
```

even though this seems excessive in the output:

```yaml
---
a: !<tag:node-tap.org,2019:symbol> "Symbol(a)"
b: "Symbol(b)"
```

This is the line doing it: https://github.com/eemeli/yaml/blob/master/src/schema/_string.js#L253-L255

If I understand this bit correctly, it's handling cases where a value would be ambiguous if unquoted, like `true`.  However, this seems like it would only be a problem if the type is established as a default; as it is, with `default: true`, Symbol objects will always be stringified with an explicit tag.

However, when I pass the `default` value through on the resolved Scalar object and let non-default values pass through unquoted, it ends up parsing as a Symbol, even without the tag.

1. Is there a way to say "no, really, this type _must_ have an explicit tag, even if the regexp matches"?
2. If such a flag is set, would it be appropriate to stringify without quoting?  And is it intelligible on parsing, that such a flag would mean "only use this type if it has that tag"?

Please let me know if I'm missing something, or if you think it's a good idea.  Thanks!

**Comment by isaacs** [comment]
Note: that also means I can't just do `!<tag:node-tap.org,2019:symbol> a` which sort of seems like a cuter representation.  But if the `test` in my type is `.*`, then anything _might_ be a symbol, so every string everywhere is double-quoted.

**Comment by isaacs** [comment]
Aha!  Thanks, I had a feeling I was missing something obvious.

This works exactly as I want:

```js
const stringType = require('yaml/dist/schema/_string.js')
module.exports = {
  class: Symbol,
  tag: 'tag:node-tap.org,2019:symbol',
  resolve (doc, item) {
    const src = stringType.resolve(doc, item)
    return Symbol(src)
  },
  stringify (item, ctx, onComment, onChompKeep) {
    return stringType.stringify(item, ctx, onComment, onChompKeep)
  },
}
```

> Eventually, it should be possible to reduce the in-document representation of a symbol using Document#setTagPrefix() to something like !js!symbol a. And if it isn't, then I need to fix something.

Yeah, I can shorten the tags that way easily enough, but since TAP doesn't include yaml _documents_ per se, only yaml _blocks_ embedded in the test output, relying on anything at the document level will break interop with other TAP parsers.

**Comment by isaacs** [comment]
Oh, maybe I spoke too soon?  If you _do_ want to use a test, and make it a default type, then it still quotes things that are that type, resulting in a string when parsing the output.  Consider this:

```js
const stringType = require('yaml/dist/schema/_string.js')
module.exports = {
  class: RegExp,
  tag: 'tag:node-tap.org,2019:regexp',
  resolve (doc, src, flags) {
    return new RegExp(src, flags)
  },
  default: true,
  test: /^\/(.*)\/([gimuy]+)$/,
  stringify (item, ctx, onComment, onChompKeep) {
    return stringType.stringify({ value: item.value.toString() }, ctx, onComment, onChompKeep)
  },
}
```

My goal here is that regular expressions dump as a scalar like `pattern: /re/g`, and then parse back in as a regular expression if they match the pattern.

However, since the resolveScalar call returns a regexp rather than a string, it always gets quoted, which means that the dump is loaded back in as a string.

```
$ node y.js
js data:
---
 { r: /re/g }
...
yamlData:
---
r: "/re/g"    <-- this is improperly casting to a string with doublequotes
...
loaded
---
 { r: '/re/g' }  <-- resulting in a string being loaded
...
dumped:
---
r: "/re/g"  <-- this is properly quoting, since it could be confused with a regexp literal
...
```

**Comment by eemeli** [comment]
You're right. The parsed-as-string check does not take into account the cases that use the string stringifier for non-string values. It's there to catch string representations of e.g. numbers or booleans being stringified, which need to be quoted in most schemas to have them also be parsed as strings. It'll need to be parameterised to stop all non-string types getting double-quoted.

**Comment by isaacs** [comment]
Maybe there needs to be a more generic `stringifyScalar()` method or something?

**Comment by eemeli** [comment]
@isaacs I updated the parsing check a bit, so it should now "just work" as well as not getting run needlessly. Have a look at the changes to see what I did? I built the test cases using your RegExp tag, hope that's okay.

**Comment by isaacs** [comment]
Cool!  But it looks like this does the right thing for regexp's, but now does the _wrong_ thing for strings that _look_ like regexps.

Here's an example: https://gist.github.com/isaacs/f1b2c012c7fc37e5e8e66e4f3b09d4bc

The regexp stays a regexp, but when the value is a string, and a plain string would be cast to something other than a string, it probably _should_ have quotes added.  (Ie, like `true` or `1` would.)

Totally fine to use any code I post here in your tests or in the module itself.  Definitely serves my interests :)

**Comment by isaacs** [comment]
Ah!  Nevermind, I missed the `Object.assign({ reqStringParse: true }, ctx)` bit.

Yes, this is working as desired now.  Thanks!

**Comment by isaacs** [comment]
So, wait.. this seems like it's in reverse.  I can set `reqStringParse: true` to make it use double-quoted scalars, but I only want that for the string type, _not_ for my custom default scalar pattern-matching type.

Since that isn't the default, that means that all I can do is force a regexp to be stringified as a double-quoted string.  But, my intention is that `{ r: /re/g }` will be stringified as `r: /re/g` and _when that regexp type exists_, `{ s: '/re/g' }` will be stringified as `s: "/re/g"` to disambiguate it from a regexp.

Does that make sense?  It seems like the default String type should be the one setting this, not the custom type.

**Comment by isaacs** [comment]
The approach in #82 might work.  It does rely on _not_ sending a pre-stringified value to stringType.stringify(), but maybe that's fine?

**Comment by eemeli** [comment]
After a bit more thought, I don't think you should support untagged (i.e. "default") RegExp values.

One of the reasons why the string stringifier is so complicated is that it has to deal with attempts to stringify strings that aren't valid plain strings, e.g. if they include a colon followed by a space `': '`. While RegExp strings are relatively easy to parse from the raw source, it doesn't make sense to break YAML semantics in order to always allow for unquoted regexp strings.

Instead, the more right thing to do here is to always tag RegExp values. Do note that in a case like this, the tag can be a local application-specific tag like `!re`, so you'd end up with a YAML representation like `!re /foo/g` or `!re "/foo: bar/"`.

I updated the parameterisation a bit; the value that you can now set in the context is `actualString: false`, which skips the typeof check and yes, does presume that implicit tags are pretty tame in what they may consume.

**Comment by isaacs** [comment]
Ah, yeah, I hadn't thought about the `/foo: bar/` case.  That's a good point.

**Comment by eemeli** [comment]
@isaacs Does this latest approach answer the needs you had? I don't think there's anything left to do before closing this, but figured I'd check before toggling its status once again.

**Comment by isaacs** [comment]
Yeah, I think it's fine.

It would perhaps be worthwhile to add a note in the docs advising that it's a bad idea to use default and test together with custom scalar types.  (Or even raise an error indicating why this is not a good idea.)
