### ISSUE TITLE
Duplicate  map keys with anchor  shouldn't be marked as error

### ISSUE THREAD

**Issue by foisonocean** [eemeli/yaml#93]
Version: v1.3.2

related issue: https://github.com/eemeli/yaml/issues/21

```javascript
import YAML from "yaml";

YAML.parse(
  `
.anchors: &anchor1
  key: value

.anchors: &anchor2
  another: prop

foo:
  bar: baz
  <<: *anchor1
  <<: *anchor2
`,
  { merge: true }
);

```

Expected: no error

**Comment by eemeli** [comment]
The error is in fact proper in this case, as the top-level object here is a mapping that would have the keys `.anchors`, `.anchors`, and `foo`. The spec [requires](https://yaml.org/spec/1.2/spec.html#id2802432) that these keys must be "unique [...] and mapped to exactly one value".

From YAML's point of view, `.anchors` is in no way special, and will be handled exactly like any other key.
