### ISSUE TITLE
Cleaning up the project's exports

### ISSUE THREAD

**Issue by eemeli** [eemeli/yaml#94]
As it turns out, our exports are a bit of a mess now. Here's how they currently look like with CommonJS (which has a few more problems than ES6 imports):
```js
const YAML = require('yaml')
const parseCST = require('yaml/parse-cst')

const { findPair, default: YAMLMap } = require('yaml/map')
const Pair = require('yaml/pair')
const Scalar = require('yaml/scalar')
const Schema = require('yaml/schema')
const { nullOptions, stringify, strOptions } = require('yaml/schema')
const YAMLSeq = require('yaml/seq')

const { binary, default: arrayOfBinaryTag } = require('yaml/types/binary')
const omapTag = require('yaml/types/omap')
const pairsTag = require('yaml/types/pairs')
const setTag = require('yaml/types/set')
const { floatTime, intTime, timestamp, default: arrayOfTimeTags } = require('yaml/types/timestamp')
```

In addition to these public exports, custom tags are rather likely to use some subset of the following non-public exports (based on the usage by the built-in tags):
```js
const { YAMLReferenceError, YAMLSemanticError, YAMLSyntaxError, YAMLWarning } = require('yaml/dist/errors')
const { Type } = require('yaml/dist/cst/Node')
const { stringifyNumber } = require('yaml/dist/schema/core')
const parseMap = require('yaml/dist/schema/parseMap')
const parseSeq = require('yaml/dist/schema/parseSeq')
const toJSON = require('yaml/dist/toJSON')
```

Furthermore, practically all of these classes and functions are available (via possibly somewhat elaborate, and mostly undocumented paths) within the core `YAML` export.

All of this got this way gradually, and (of course) with good intentions, but it's still a mess. I'd like to clean it up and make sure that the exports that are useful for custom tags are properly exposed, while regularising the structure a bit. It would be really nice to make that happen while not breaking any of the public exports either.

This issue will track this cleanup effort, as I don't yet have a solution ready for the situation.

**Comment by eemeli** [comment]
Working draft for the update:

```js
const YAML = require('yaml')
const parseCST = require('yaml/parse-cst')

const {
  binary, floatTime, intTime, timestamp,
  omap, pairs, set,
  nullOptions, strOptions,
  Map, YAMLMap, // synonyms
  Pair,
  Scalar,
  Schema,
  Seq, YAMLSeq // synonyms
} = require('yaml/types')

const {
  findPair,
  parseMap, parseSeq,
  stringifyNumber, stringifyString,
  toJSON,
  Type,
  YAMLReferenceError, YAMLSemanticError, YAMLSyntaxError, YAMLWarning
} = require('yaml/util')
```

**Comment by isaacs** [comment]
Hm, it looks like binary, set, and omap aren't present in `require('yaml/types')`.  Did they land somewhere else?

**Comment by eemeli** [comment]
No, they are now no longer directly published. Instead, use the built-in types' [string identifiers](https://eemeli.org/yaml/#custom-data-types) in the `customTags` option.

Internally, they're available at `yaml/dist/tags`, but I couldn't come up with a use case for publicly exporting them, other than to then use them directly as custom tags. Or did I miss something?

**Comment by isaacs** [comment]
Ah, ok, so instead of putting `require('yaml/types/omap')` in the set, for example, I just put `'omap'`.  That seems to work.  Thanks!
