### ISSUE TITLE
How do you set the tag stringifier options when YAML is imported in node?

### ISSUE THREAD

**Issue by MightyRevenge** [eemeli/yaml#95]
I have this in my `express.js` backend:
`const YAML = require('yaml');`

How do you set `strOptions.defaultType = 'QUOTE_SINGLE'` from here on out? (related to: https://eemeli.org/yaml/#tag-stringifier-options)

**Comment by eemeli** [comment]
As mentioned in the sidebar of the docs section you linked to, `strOptions` is available as an export from `'yaml/schema'`.
