### ISSUE TITLE
error.source.context is often too big to be helpful

### ISSUE THREAD

**Issue by isaacs** [eemeli/yaml#96]
I'm finding myself in a few cases where error.source.context is a pretty large object.  Printing this out (with a logger that includes the source text of functions) results in over 15,000 lines of debugging, which is way too much.  Node's built-in console.log() is still several hundred lines.

I can see how this is helpful when working on bugs and features in YAML itself, but it's pretty excessive otherwise.  Perhaps it could be omitted when cwd is not the YAML project?

**Comment by eemeli** [comment]
Sorry for having left this issue unanswered before now. The error `source` is in fact the corresponding CST node, and its `context` is required by some parsing stages, which will continue even after the point at which the error has occurred. So it's a bit difficult to modify, especially as it's required by the internals of the `getRangeAsLinePos` getter.

What might work is an optional post-processing of the errors and warnings, which would fetch the errors' line positions and drop most of the CST source node data. Optional, so as not to necessitate a major version bump.

**Comment by isaacs** [comment]
An optional error/warning cleanup step would probably solve this, yes.

**Comment by eemeli** [comment]
Added the `prettyErrors` option (default `false`), which drops `source` and adds `nodeType`, `range` and `linePos` to errors.
